/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AxiosInstance, AxiosPromise, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
import { BASE_PATH, BaseAPI, operationServerMap, type RequestArgs } from '../base';
import {
  DUMMY_BASE_URL,
  assertParamExists,
  createRequestFunction,
  serializeDataIfNeeded,
  setBearerAuthToObject,
  setSearchParams,
  toPathString,
} from '../common';
import type { Configuration } from '../configuration';
import type {
  ConditionSetCreate,
  ConditionSetRead,
  ConditionSetType,
  ConditionSetUpdate,
  ResponseListConditionSetsV2SchemaProjIdEnvIdConditionSetsGet,
} from '../types';
/**
 * ConditionSetsApi - axios parameter creator
 */
export const ConditionSetsApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Creates a new condition set (can be either a user set or a resource set).
     * @summary Create Condition Set
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {ConditionSetCreate} conditionSetCreate
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    createConditionSet: async (
      projId: string,
      envId: string,
      conditionSetCreate: ConditionSetCreate,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'projId' is not null or undefined
      assertParamExists('createConditionSet', 'projId', projId);
      // verify required parameter 'envId' is not null or undefined
      assertParamExists('createConditionSet', 'envId', envId);
      // verify required parameter 'conditionSetCreate' is not null or undefined
      assertParamExists('createConditionSet', 'conditionSetCreate', conditionSetCreate);
      const localVarPath = `/v2/schema/{proj_id}/{env_id}/condition_sets`
        .replace('{proj_id}', encodeURIComponent(String(projId)))
        .replace('{env_id}', encodeURIComponent(String(envId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';
      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        conditionSetCreate,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Deletes a condition set and all its related data. This includes any permissions granted to said condition set (i.e: any matching condition set users_with_role).
     * @summary Delete Condition Set
     * @param {string} conditionSetId Either the unique id of the condition set, or the URL-friendly key of the condition set (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    deleteConditionSet: async (
      conditionSetId: string,
      projId: string,
      envId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'conditionSetId' is not null or undefined
      assertParamExists('deleteConditionSet', 'conditionSetId', conditionSetId);
      // verify required parameter 'projId' is not null or undefined
      assertParamExists('deleteConditionSet', 'projId', projId);
      // verify required parameter 'envId' is not null or undefined
      assertParamExists('deleteConditionSet', 'envId', envId);
      const localVarPath = `/v2/schema/{proj_id}/{env_id}/condition_sets/{condition_set_id}`
        .replace('{condition_set_id}', encodeURIComponent(String(conditionSetId)))
        .replace('{proj_id}', encodeURIComponent(String(projId)))
        .replace('{env_id}', encodeURIComponent(String(envId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Gets a single condition set, if such condition set exists.
     * @summary Get Condition Set
     * @param {string} conditionSetId Either the unique id of the condition set, or the URL-friendly key of the condition set (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    getConditionSet: async (
      conditionSetId: string,
      projId: string,
      envId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'conditionSetId' is not null or undefined
      assertParamExists('getConditionSet', 'conditionSetId', conditionSetId);
      // verify required parameter 'projId' is not null or undefined
      assertParamExists('getConditionSet', 'projId', projId);
      // verify required parameter 'envId' is not null or undefined
      assertParamExists('getConditionSet', 'envId', envId);
      const localVarPath = `/v2/schema/{proj_id}/{env_id}/condition_sets/{condition_set_id}`
        .replace('{condition_set_id}', encodeURIComponent(String(conditionSetId)))
        .replace('{proj_id}', encodeURIComponent(String(projId)))
        .replace('{env_id}', encodeURIComponent(String(envId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Gets all ancestors (parent, parent of parent, and so on)
     * @summary Get Condition Set Ancestors
     * @param {string} conditionSetId Either the unique id of the condition set, or the URL-friendly key of the condition set (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {number} [page] Page number of the results to fetch, starting at 1.
     * @param {number} [perPage] The number of results per page (max 100).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    getConditionSetAncestors: async (
      conditionSetId: string,
      projId: string,
      envId: string,
      page?: number,
      perPage?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'conditionSetId' is not null or undefined
      assertParamExists('getConditionSetAncestors', 'conditionSetId', conditionSetId);
      // verify required parameter 'projId' is not null or undefined
      assertParamExists('getConditionSetAncestors', 'projId', projId);
      // verify required parameter 'envId' is not null or undefined
      assertParamExists('getConditionSetAncestors', 'envId', envId);
      const localVarPath =
        `/v2/schema/{proj_id}/{env_id}/condition_sets/{condition_set_id}/ancestors`
          .replace('{condition_set_id}', encodeURIComponent(String(conditionSetId)))
          .replace('{proj_id}', encodeURIComponent(String(projId)))
          .replace('{env_id}', encodeURIComponent(String(envId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (page !== undefined) {
        localVarQueryParameter['page'] = page;
      }

      if (perPage !== undefined) {
        localVarQueryParameter['per_page'] = perPage;
      }

      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Gets all descendants (children, children of children, and so on)
     * @summary Get Condition Set Descendants
     * @param {string} conditionSetId Either the unique id of the condition set, or the URL-friendly key of the condition set (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {number} [page] Page number of the results to fetch, starting at 1.
     * @param {number} [perPage] The number of results per page (max 100).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    getConditionSetDescendants: async (
      conditionSetId: string,
      projId: string,
      envId: string,
      page?: number,
      perPage?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'conditionSetId' is not null or undefined
      assertParamExists('getConditionSetDescendants', 'conditionSetId', conditionSetId);
      // verify required parameter 'projId' is not null or undefined
      assertParamExists('getConditionSetDescendants', 'projId', projId);
      // verify required parameter 'envId' is not null or undefined
      assertParamExists('getConditionSetDescendants', 'envId', envId);
      const localVarPath =
        `/v2/schema/{proj_id}/{env_id}/condition_sets/{condition_set_id}/descendants`
          .replace('{condition_set_id}', encodeURIComponent(String(conditionSetId)))
          .replace('{proj_id}', encodeURIComponent(String(projId)))
          .replace('{env_id}', encodeURIComponent(String(envId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (page !== undefined) {
        localVarQueryParameter['page'] = page;
      }

      if (perPage !== undefined) {
        localVarQueryParameter['per_page'] = perPage;
      }

      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Lists all condition sets matching a filter.
     * @summary List Condition Sets
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {string} [search] Text search for the condition sets name or key
     * @param {ConditionSetType} [type] if provided, will return only the condition sets of the specified type. e.g: only user sets.
     * @param {boolean} [includeTotalCount] Include total count in response
     * @param {number} [page] Page number of the results to fetch, starting at 1.
     * @param {number} [perPage] The number of results per page (max 100).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    listConditionSets: async (
      projId: string,
      envId: string,
      search?: string,
      type?: ConditionSetType,
      includeTotalCount?: boolean,
      page?: number,
      perPage?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'projId' is not null or undefined
      assertParamExists('listConditionSets', 'projId', projId);
      // verify required parameter 'envId' is not null or undefined
      assertParamExists('listConditionSets', 'envId', envId);
      const localVarPath = `/v2/schema/{proj_id}/{env_id}/condition_sets`
        .replace('{proj_id}', encodeURIComponent(String(projId)))
        .replace('{env_id}', encodeURIComponent(String(envId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (search !== undefined) {
        localVarQueryParameter['search'] = search;
      }

      if (type !== undefined) {
        localVarQueryParameter['type'] = type;
      }

      if (includeTotalCount !== undefined) {
        localVarQueryParameter['include_total_count'] = includeTotalCount;
      }

      if (page !== undefined) {
        localVarQueryParameter['page'] = page;
      }

      if (perPage !== undefined) {
        localVarQueryParameter['per_page'] = perPage;
      }

      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Partially updates a condition set. Fields that will be provided will be completely overwritten.
     * @summary Update Condition Set
     * @param {string} conditionSetId Either the unique id of the condition set, or the URL-friendly key of the condition set (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {ConditionSetUpdate} conditionSetUpdate
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    updateConditionSet: async (
      conditionSetId: string,
      projId: string,
      envId: string,
      conditionSetUpdate: ConditionSetUpdate,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'conditionSetId' is not null or undefined
      assertParamExists('updateConditionSet', 'conditionSetId', conditionSetId);
      // verify required parameter 'projId' is not null or undefined
      assertParamExists('updateConditionSet', 'projId', projId);
      // verify required parameter 'envId' is not null or undefined
      assertParamExists('updateConditionSet', 'envId', envId);
      // verify required parameter 'conditionSetUpdate' is not null or undefined
      assertParamExists('updateConditionSet', 'conditionSetUpdate', conditionSetUpdate);
      const localVarPath = `/v2/schema/{proj_id}/{env_id}/condition_sets/{condition_set_id}`
        .replace('{condition_set_id}', encodeURIComponent(String(conditionSetId)))
        .replace('{proj_id}', encodeURIComponent(String(projId)))
        .replace('{env_id}', encodeURIComponent(String(envId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';
      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        conditionSetUpdate,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ConditionSetsApi - functional programming interface
 */
export const ConditionSetsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = ConditionSetsApiAxiosParamCreator(configuration);
  return {
    /**
     * Creates a new condition set (can be either a user set or a resource set).
     * @summary Create Condition Set
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {ConditionSetCreate} conditionSetCreate
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async createConditionSet(
      projId: string,
      envId: string,
      conditionSetCreate: ConditionSetCreate,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConditionSetRead>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createConditionSet(
        projId,
        envId,
        conditionSetCreate,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ConditionSetsApi.createConditionSet']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Deletes a condition set and all its related data. This includes any permissions granted to said condition set (i.e: any matching condition set users_with_role).
     * @summary Delete Condition Set
     * @param {string} conditionSetId Either the unique id of the condition set, or the URL-friendly key of the condition set (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async deleteConditionSet(
      conditionSetId: string,
      projId: string,
      envId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteConditionSet(
        conditionSetId,
        projId,
        envId,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ConditionSetsApi.deleteConditionSet']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Gets a single condition set, if such condition set exists.
     * @summary Get Condition Set
     * @param {string} conditionSetId Either the unique id of the condition set, or the URL-friendly key of the condition set (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async getConditionSet(
      conditionSetId: string,
      projId: string,
      envId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConditionSetRead>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getConditionSet(
        conditionSetId,
        projId,
        envId,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ConditionSetsApi.getConditionSet']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Gets all ancestors (parent, parent of parent, and so on)
     * @summary Get Condition Set Ancestors
     * @param {string} conditionSetId Either the unique id of the condition set, or the URL-friendly key of the condition set (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {number} [page] Page number of the results to fetch, starting at 1.
     * @param {number} [perPage] The number of results per page (max 100).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async getConditionSetAncestors(
      conditionSetId: string,
      projId: string,
      envId: string,
      page?: number,
      perPage?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ConditionSetRead>>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getConditionSetAncestors(
        conditionSetId,
        projId,
        envId,
        page,
        perPage,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ConditionSetsApi.getConditionSetAncestors']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Gets all descendants (children, children of children, and so on)
     * @summary Get Condition Set Descendants
     * @param {string} conditionSetId Either the unique id of the condition set, or the URL-friendly key of the condition set (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {number} [page] Page number of the results to fetch, starting at 1.
     * @param {number} [perPage] The number of results per page (max 100).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async getConditionSetDescendants(
      conditionSetId: string,
      projId: string,
      envId: string,
      page?: number,
      perPage?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ConditionSetRead>>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getConditionSetDescendants(
        conditionSetId,
        projId,
        envId,
        page,
        perPage,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ConditionSetsApi.getConditionSetDescendants']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Lists all condition sets matching a filter.
     * @summary List Condition Sets
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {string} [search] Text search for the condition sets name or key
     * @param {ConditionSetType} [type] if provided, will return only the condition sets of the specified type. e.g: only user sets.
     * @param {boolean} [includeTotalCount] Include total count in response
     * @param {number} [page] Page number of the results to fetch, starting at 1.
     * @param {number} [perPage] The number of results per page (max 100).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async listConditionSets(
      projId: string,
      envId: string,
      search?: string,
      type?: ConditionSetType,
      includeTotalCount?: boolean,
      page?: number,
      perPage?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<ResponseListConditionSetsV2SchemaProjIdEnvIdConditionSetsGet>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.listConditionSets(
        projId,
        envId,
        search,
        type,
        includeTotalCount,
        page,
        perPage,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ConditionSetsApi.listConditionSets']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Partially updates a condition set. Fields that will be provided will be completely overwritten.
     * @summary Update Condition Set
     * @param {string} conditionSetId Either the unique id of the condition set, or the URL-friendly key of the condition set (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {ConditionSetUpdate} conditionSetUpdate
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async updateConditionSet(
      conditionSetId: string,
      projId: string,
      envId: string,
      conditionSetUpdate: ConditionSetUpdate,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConditionSetRead>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateConditionSet(
        conditionSetId,
        projId,
        envId,
        conditionSetUpdate,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ConditionSetsApi.updateConditionSet']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * ConditionSetsApi - factory interface
 */
export const ConditionSetsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = ConditionSetsApiFp(configuration);
  return {
    /**
     * Creates a new condition set (can be either a user set or a resource set).
     * @summary Create Condition Set
     * @param {ConditionSetsApiCreateConditionSetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    createConditionSet(
      requestParameters: ConditionSetsApiCreateConditionSetRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ConditionSetRead> {
      return localVarFp
        .createConditionSet(
          requestParameters.projId,
          requestParameters.envId,
          requestParameters.conditionSetCreate,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Deletes a condition set and all its related data. This includes any permissions granted to said condition set (i.e: any matching condition set users_with_role).
     * @summary Delete Condition Set
     * @param {ConditionSetsApiDeleteConditionSetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    deleteConditionSet(
      requestParameters: ConditionSetsApiDeleteConditionSetRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .deleteConditionSet(
          requestParameters.conditionSetId,
          requestParameters.projId,
          requestParameters.envId,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Gets a single condition set, if such condition set exists.
     * @summary Get Condition Set
     * @param {ConditionSetsApiGetConditionSetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    getConditionSet(
      requestParameters: ConditionSetsApiGetConditionSetRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ConditionSetRead> {
      return localVarFp
        .getConditionSet(
          requestParameters.conditionSetId,
          requestParameters.projId,
          requestParameters.envId,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Gets all ancestors (parent, parent of parent, and so on)
     * @summary Get Condition Set Ancestors
     * @param {ConditionSetsApiGetConditionSetAncestorsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    getConditionSetAncestors(
      requestParameters: ConditionSetsApiGetConditionSetAncestorsRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Array<ConditionSetRead>> {
      return localVarFp
        .getConditionSetAncestors(
          requestParameters.conditionSetId,
          requestParameters.projId,
          requestParameters.envId,
          requestParameters.page,
          requestParameters.perPage,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Gets all descendants (children, children of children, and so on)
     * @summary Get Condition Set Descendants
     * @param {ConditionSetsApiGetConditionSetDescendantsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    getConditionSetDescendants(
      requestParameters: ConditionSetsApiGetConditionSetDescendantsRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Array<ConditionSetRead>> {
      return localVarFp
        .getConditionSetDescendants(
          requestParameters.conditionSetId,
          requestParameters.projId,
          requestParameters.envId,
          requestParameters.page,
          requestParameters.perPage,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Lists all condition sets matching a filter.
     * @summary List Condition Sets
     * @param {ConditionSetsApiListConditionSetsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    listConditionSets(
      requestParameters: ConditionSetsApiListConditionSetsRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ResponseListConditionSetsV2SchemaProjIdEnvIdConditionSetsGet> {
      return localVarFp
        .listConditionSets(
          requestParameters.projId,
          requestParameters.envId,
          requestParameters.search,
          requestParameters.type,
          requestParameters.includeTotalCount,
          requestParameters.page,
          requestParameters.perPage,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Partially updates a condition set. Fields that will be provided will be completely overwritten.
     * @summary Update Condition Set
     * @param {ConditionSetsApiUpdateConditionSetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    updateConditionSet(
      requestParameters: ConditionSetsApiUpdateConditionSetRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ConditionSetRead> {
      return localVarFp
        .updateConditionSet(
          requestParameters.conditionSetId,
          requestParameters.projId,
          requestParameters.envId,
          requestParameters.conditionSetUpdate,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for createConditionSet operation in ConditionSetsApi.
 */
export interface ConditionSetsApiCreateConditionSetRequest {
  /**
   * Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
   */
  readonly projId: string;

  /**
   * Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
   */
  readonly envId: string;

  readonly conditionSetCreate: ConditionSetCreate;
}

/**
 * Request parameters for deleteConditionSet operation in ConditionSetsApi.
 */
export interface ConditionSetsApiDeleteConditionSetRequest {
  /**
   * Either the unique id of the condition set, or the URL-friendly key of the condition set (i.e: the \&quot;slug\&quot;).
   */
  readonly conditionSetId: string;

  /**
   * Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
   */
  readonly projId: string;

  /**
   * Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
   */
  readonly envId: string;
}

/**
 * Request parameters for getConditionSet operation in ConditionSetsApi.
 */
export interface ConditionSetsApiGetConditionSetRequest {
  /**
   * Either the unique id of the condition set, or the URL-friendly key of the condition set (i.e: the \&quot;slug\&quot;).
   */
  readonly conditionSetId: string;

  /**
   * Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
   */
  readonly projId: string;

  /**
   * Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
   */
  readonly envId: string;
}

/**
 * Request parameters for getConditionSetAncestors operation in ConditionSetsApi.
 */
export interface ConditionSetsApiGetConditionSetAncestorsRequest {
  /**
   * Either the unique id of the condition set, or the URL-friendly key of the condition set (i.e: the \&quot;slug\&quot;).
   */
  readonly conditionSetId: string;

  /**
   * Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
   */
  readonly projId: string;

  /**
   * Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
   */
  readonly envId: string;

  /**
   * Page number of the results to fetch, starting at 1.
   */
  readonly page?: number;

  /**
   * The number of results per page (max 100).
   */
  readonly perPage?: number;
}

/**
 * Request parameters for getConditionSetDescendants operation in ConditionSetsApi.
 */
export interface ConditionSetsApiGetConditionSetDescendantsRequest {
  /**
   * Either the unique id of the condition set, or the URL-friendly key of the condition set (i.e: the \&quot;slug\&quot;).
   */
  readonly conditionSetId: string;

  /**
   * Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
   */
  readonly projId: string;

  /**
   * Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
   */
  readonly envId: string;

  /**
   * Page number of the results to fetch, starting at 1.
   */
  readonly page?: number;

  /**
   * The number of results per page (max 100).
   */
  readonly perPage?: number;
}

/**
 * Request parameters for listConditionSets operation in ConditionSetsApi.
 */
export interface ConditionSetsApiListConditionSetsRequest {
  /**
   * Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
   */
  readonly projId: string;

  /**
   * Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
   */
  readonly envId: string;

  /**
   * Text search for the condition sets name or key
   */
  readonly search?: string;

  /**
   * if provided, will return only the condition sets of the specified type. e.g: only user sets.
   */
  readonly type?: ConditionSetType;

  /**
   * Include total count in response
   */
  readonly includeTotalCount?: boolean;

  /**
   * Page number of the results to fetch, starting at 1.
   */
  readonly page?: number;

  /**
   * The number of results per page (max 100).
   */
  readonly perPage?: number;
}

/**
 * Request parameters for updateConditionSet operation in ConditionSetsApi.
 */
export interface ConditionSetsApiUpdateConditionSetRequest {
  /**
   * Either the unique id of the condition set, or the URL-friendly key of the condition set (i.e: the \&quot;slug\&quot;).
   */
  readonly conditionSetId: string;

  /**
   * Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
   */
  readonly projId: string;

  /**
   * Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
   */
  readonly envId: string;

  readonly conditionSetUpdate: ConditionSetUpdate;
}

/**
 * ConditionSetsApi - object-oriented interface
 */
export class ConditionSetsApi extends BaseAPI {
  /**
   * Creates a new condition set (can be either a user set or a resource set).
   * @summary Create Condition Set
   * @param {ConditionSetsApiCreateConditionSetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public createConditionSet(
    requestParameters: ConditionSetsApiCreateConditionSetRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ConditionSetsApiFp(this.configuration)
      .createConditionSet(
        requestParameters.projId,
        requestParameters.envId,
        requestParameters.conditionSetCreate,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Deletes a condition set and all its related data. This includes any permissions granted to said condition set (i.e: any matching condition set users_with_role).
   * @summary Delete Condition Set
   * @param {ConditionSetsApiDeleteConditionSetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public deleteConditionSet(
    requestParameters: ConditionSetsApiDeleteConditionSetRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ConditionSetsApiFp(this.configuration)
      .deleteConditionSet(
        requestParameters.conditionSetId,
        requestParameters.projId,
        requestParameters.envId,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Gets a single condition set, if such condition set exists.
   * @summary Get Condition Set
   * @param {ConditionSetsApiGetConditionSetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public getConditionSet(
    requestParameters: ConditionSetsApiGetConditionSetRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ConditionSetsApiFp(this.configuration)
      .getConditionSet(
        requestParameters.conditionSetId,
        requestParameters.projId,
        requestParameters.envId,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Gets all ancestors (parent, parent of parent, and so on)
   * @summary Get Condition Set Ancestors
   * @param {ConditionSetsApiGetConditionSetAncestorsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public getConditionSetAncestors(
    requestParameters: ConditionSetsApiGetConditionSetAncestorsRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ConditionSetsApiFp(this.configuration)
      .getConditionSetAncestors(
        requestParameters.conditionSetId,
        requestParameters.projId,
        requestParameters.envId,
        requestParameters.page,
        requestParameters.perPage,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Gets all descendants (children, children of children, and so on)
   * @summary Get Condition Set Descendants
   * @param {ConditionSetsApiGetConditionSetDescendantsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public getConditionSetDescendants(
    requestParameters: ConditionSetsApiGetConditionSetDescendantsRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ConditionSetsApiFp(this.configuration)
      .getConditionSetDescendants(
        requestParameters.conditionSetId,
        requestParameters.projId,
        requestParameters.envId,
        requestParameters.page,
        requestParameters.perPage,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Lists all condition sets matching a filter.
   * @summary List Condition Sets
   * @param {ConditionSetsApiListConditionSetsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public listConditionSets(
    requestParameters: ConditionSetsApiListConditionSetsRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ConditionSetsApiFp(this.configuration)
      .listConditionSets(
        requestParameters.projId,
        requestParameters.envId,
        requestParameters.search,
        requestParameters.type,
        requestParameters.includeTotalCount,
        requestParameters.page,
        requestParameters.perPage,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Partially updates a condition set. Fields that will be provided will be completely overwritten.
   * @summary Update Condition Set
   * @param {ConditionSetsApiUpdateConditionSetRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public updateConditionSet(
    requestParameters: ConditionSetsApiUpdateConditionSetRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ConditionSetsApiFp(this.configuration)
      .updateConditionSet(
        requestParameters.conditionSetId,
        requestParameters.projId,
        requestParameters.envId,
        requestParameters.conditionSetUpdate,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
