/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AxiosInstance, AxiosPromise, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
import { BASE_PATH, BaseAPI, operationServerMap, type RequestArgs } from '../base';
import {
  DUMMY_BASE_URL,
  assertParamExists,
  createRequestFunction,
  setBearerAuthToObject,
  setSearchParams,
  toPathString,
} from '../common';
import type { Configuration } from '../configuration';
import type { TaskResultOrgExportResult } from '../types';
/**
 * DataExportApi - axios parameter creator
 */
export const DataExportApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Poll an export started by `POST /v2/data-export`. While it runs the status is `processing`; on `success` the `result` carries a short-lived presigned `download_url`; on `failure` the `error` explains why (e.g. the org is too large for the self-service export). Only exports of your own organization are visible.
     * @summary Get the status / download URL of an export
     * @param {string} taskId The export task id from the POST response
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    getOrganizationExport: async (
      taskId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'taskId' is not null or undefined
      assertParamExists('getOrganizationExport', 'taskId', taskId);
      const localVarPath = `/v2/data-export/{task_id}`.replace(
        '{task_id}',
        encodeURIComponent(String(taskId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Start a background export of **your** organization\'s data and return a task id. Poll `GET /v2/data-export/{task_id}` until it succeeds to get a short-lived download URL for the `permit-org-export-<org>-<ts>.tar.gz` (one `data/<table>.csv` per table + `manifest.json`).  Requires an Organization API key with ADMIN access; write/read-only keys are rejected. The organization is taken from the key, so this only ever exports your own organization. The archive contains your plaintext API-key secrets (so a self-hosted import keeps working without re-issuing keys) — treat the download URL and the file as credentials.
     * @summary Start an export of your organization\'s data
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    startOrganizationExport: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/v2/data-export`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * DataExportApi - functional programming interface
 */
export const DataExportApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = DataExportApiAxiosParamCreator(configuration);
  return {
    /**
     * Poll an export started by `POST /v2/data-export`. While it runs the status is `processing`; on `success` the `result` carries a short-lived presigned `download_url`; on `failure` the `error` explains why (e.g. the org is too large for the self-service export). Only exports of your own organization are visible.
     * @summary Get the status / download URL of an export
     * @param {string} taskId The export task id from the POST response
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async getOrganizationExport(
      taskId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskResultOrgExportResult>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getOrganizationExport(
        taskId,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['DataExportApi.getOrganizationExport']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Start a background export of **your** organization\'s data and return a task id. Poll `GET /v2/data-export/{task_id}` until it succeeds to get a short-lived download URL for the `permit-org-export-<org>-<ts>.tar.gz` (one `data/<table>.csv` per table + `manifest.json`).  Requires an Organization API key with ADMIN access; write/read-only keys are rejected. The organization is taken from the key, so this only ever exports your own organization. The archive contains your plaintext API-key secrets (so a self-hosted import keeps working without re-issuing keys) — treat the download URL and the file as credentials.
     * @summary Start an export of your organization\'s data
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async startOrganizationExport(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<TaskResultOrgExportResult>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.startOrganizationExport(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['DataExportApi.startOrganizationExport']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * DataExportApi - factory interface
 */
export const DataExportApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = DataExportApiFp(configuration);
  return {
    /**
     * Poll an export started by `POST /v2/data-export`. While it runs the status is `processing`; on `success` the `result` carries a short-lived presigned `download_url`; on `failure` the `error` explains why (e.g. the org is too large for the self-service export). Only exports of your own organization are visible.
     * @summary Get the status / download URL of an export
     * @param {DataExportApiGetOrganizationExportRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    getOrganizationExport(
      requestParameters: DataExportApiGetOrganizationExportRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<TaskResultOrgExportResult> {
      return localVarFp
        .getOrganizationExport(requestParameters.taskId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Start a background export of **your** organization\'s data and return a task id. Poll `GET /v2/data-export/{task_id}` until it succeeds to get a short-lived download URL for the `permit-org-export-<org>-<ts>.tar.gz` (one `data/<table>.csv` per table + `manifest.json`).  Requires an Organization API key with ADMIN access; write/read-only keys are rejected. The organization is taken from the key, so this only ever exports your own organization. The archive contains your plaintext API-key secrets (so a self-hosted import keeps working without re-issuing keys) — treat the download URL and the file as credentials.
     * @summary Start an export of your organization\'s data
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    startOrganizationExport(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<TaskResultOrgExportResult> {
      return localVarFp
        .startOrganizationExport(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for getOrganizationExport operation in DataExportApi.
 */
export interface DataExportApiGetOrganizationExportRequest {
  /**
   * The export task id from the POST response
   */
  readonly taskId: string;
}

/**
 * DataExportApi - object-oriented interface
 */
export class DataExportApi extends BaseAPI {
  /**
   * Poll an export started by `POST /v2/data-export`. While it runs the status is `processing`; on `success` the `result` carries a short-lived presigned `download_url`; on `failure` the `error` explains why (e.g. the org is too large for the self-service export). Only exports of your own organization are visible.
   * @summary Get the status / download URL of an export
   * @param {DataExportApiGetOrganizationExportRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public getOrganizationExport(
    requestParameters: DataExportApiGetOrganizationExportRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return DataExportApiFp(this.configuration)
      .getOrganizationExport(requestParameters.taskId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Start a background export of **your** organization\'s data and return a task id. Poll `GET /v2/data-export/{task_id}` until it succeeds to get a short-lived download URL for the `permit-org-export-<org>-<ts>.tar.gz` (one `data/<table>.csv` per table + `manifest.json`).  Requires an Organization API key with ADMIN access; write/read-only keys are rejected. The organization is taken from the key, so this only ever exports your own organization. The archive contains your plaintext API-key secrets (so a self-hosted import keeps working without re-issuing keys) — treat the download URL and the file as credentials.
   * @summary Start an export of your organization\'s data
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public startOrganizationExport(options?: RawAxiosRequestConfig) {
    return DataExportApiFp(this.configuration)
      .startOrganizationExport(options)
      .then((request) => request(this.axios, this.basePath));
  }
}
