/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AxiosInstance, AxiosPromise, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
import { BASE_PATH, BaseAPI, operationServerMap, type RequestArgs } from '../base';
import {
  DUMMY_BASE_URL,
  assertParamExists,
  createRequestFunction,
  serializeDataIfNeeded,
  setBearerAuthToObject,
  setSearchParams,
  toPathString,
} from '../common';
import type { Configuration } from '../configuration';
import type { InviteCreate, InviteRead, MultiInviteResult } from '../types';
/**
 * InvitesApi - axios parameter creator
 */
export const InvitesApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Cancels an invite that was sent to a new member.
     * @summary Cancel Invite
     * @param {string} orgId Either the unique id of the organization, or the URL-friendly key of the organization (i.e: the \&quot;slug\&quot;).
     * @param {string} inviteId Id of the invite to cancel
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    cancelInvite: async (
      orgId: string,
      inviteId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'orgId' is not null or undefined
      assertParamExists('cancelInvite', 'orgId', orgId);
      // verify required parameter 'inviteId' is not null or undefined
      assertParamExists('cancelInvite', 'inviteId', inviteId);
      const localVarPath = `/v2/orgs/{org_id}/invites/{invite_id}`
        .replace('{org_id}', encodeURIComponent(String(orgId)))
        .replace('{invite_id}', encodeURIComponent(String(inviteId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Invite new members into the organization.
     * @summary Invite Members To Organization
     * @param {string} orgId Either the unique id of the organization, or the URL-friendly key of the organization (i.e: the \&quot;slug\&quot;).
     * @param {Array<InviteCreate>} inviteCreate
     * @param {string} [inviterName]
     * @param {string} [inviterEmail]
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    inviteMembersToOrganization: async (
      orgId: string,
      inviteCreate: Array<InviteCreate>,
      inviterName?: string,
      inviterEmail?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'orgId' is not null or undefined
      assertParamExists('inviteMembersToOrganization', 'orgId', orgId);
      // verify required parameter 'inviteCreate' is not null or undefined
      assertParamExists('inviteMembersToOrganization', 'inviteCreate', inviteCreate);
      const localVarPath = `/v2/orgs/{org_id}/invites`.replace(
        '{org_id}',
        encodeURIComponent(String(orgId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (inviterName !== undefined) {
        localVarQueryParameter['inviter_name'] = inviterName;
      }

      if (inviterEmail !== undefined) {
        localVarQueryParameter['inviter_email'] = inviterEmail;
      }

      localVarHeaderParameter['Content-Type'] = 'application/json';
      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        inviteCreate,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Lists pending organization invites
     * @summary List Organization Invites
     * @param {string} orgId Either the unique id of the organization, or the URL-friendly key of the organization (i.e: the \&quot;slug\&quot;).
     * @param {number} [page] Page number of the results to fetch, starting at 1.
     * @param {number} [perPage] The number of results per page (max 100).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    listOrganizationInvites: async (
      orgId: string,
      page?: number,
      perPage?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'orgId' is not null or undefined
      assertParamExists('listOrganizationInvites', 'orgId', orgId);
      const localVarPath = `/v2/orgs/{org_id}/invites`.replace(
        '{org_id}',
        encodeURIComponent(String(orgId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (page !== undefined) {
        localVarQueryParameter['page'] = page;
      }

      if (perPage !== undefined) {
        localVarQueryParameter['per_page'] = perPage;
      }

      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * InvitesApi - functional programming interface
 */
export const InvitesApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = InvitesApiAxiosParamCreator(configuration);
  return {
    /**
     * Cancels an invite that was sent to a new member.
     * @summary Cancel Invite
     * @param {string} orgId Either the unique id of the organization, or the URL-friendly key of the organization (i.e: the \&quot;slug\&quot;).
     * @param {string} inviteId Id of the invite to cancel
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async cancelInvite(
      orgId: string,
      inviteId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.cancelInvite(
        orgId,
        inviteId,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['InvitesApi.cancelInvite']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Invite new members into the organization.
     * @summary Invite Members To Organization
     * @param {string} orgId Either the unique id of the organization, or the URL-friendly key of the organization (i.e: the \&quot;slug\&quot;).
     * @param {Array<InviteCreate>} inviteCreate
     * @param {string} [inviterName]
     * @param {string} [inviterEmail]
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async inviteMembersToOrganization(
      orgId: string,
      inviteCreate: Array<InviteCreate>,
      inviterName?: string,
      inviterEmail?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MultiInviteResult>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.inviteMembersToOrganization(
        orgId,
        inviteCreate,
        inviterName,
        inviterEmail,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['InvitesApi.inviteMembersToOrganization']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Lists pending organization invites
     * @summary List Organization Invites
     * @param {string} orgId Either the unique id of the organization, or the URL-friendly key of the organization (i.e: the \&quot;slug\&quot;).
     * @param {number} [page] Page number of the results to fetch, starting at 1.
     * @param {number} [perPage] The number of results per page (max 100).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async listOrganizationInvites(
      orgId: string,
      page?: number,
      perPage?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<InviteRead>>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.listOrganizationInvites(
        orgId,
        page,
        perPage,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['InvitesApi.listOrganizationInvites']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * InvitesApi - factory interface
 */
export const InvitesApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = InvitesApiFp(configuration);
  return {
    /**
     * Cancels an invite that was sent to a new member.
     * @summary Cancel Invite
     * @param {InvitesApiCancelInviteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    cancelInvite(
      requestParameters: InvitesApiCancelInviteRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .cancelInvite(requestParameters.orgId, requestParameters.inviteId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Invite new members into the organization.
     * @summary Invite Members To Organization
     * @param {InvitesApiInviteMembersToOrganizationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    inviteMembersToOrganization(
      requestParameters: InvitesApiInviteMembersToOrganizationRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<MultiInviteResult> {
      return localVarFp
        .inviteMembersToOrganization(
          requestParameters.orgId,
          requestParameters.inviteCreate,
          requestParameters.inviterName,
          requestParameters.inviterEmail,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Lists pending organization invites
     * @summary List Organization Invites
     * @param {InvitesApiListOrganizationInvitesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    listOrganizationInvites(
      requestParameters: InvitesApiListOrganizationInvitesRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Array<InviteRead>> {
      return localVarFp
        .listOrganizationInvites(
          requestParameters.orgId,
          requestParameters.page,
          requestParameters.perPage,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for cancelInvite operation in InvitesApi.
 */
export interface InvitesApiCancelInviteRequest {
  /**
   * Either the unique id of the organization, or the URL-friendly key of the organization (i.e: the \&quot;slug\&quot;).
   */
  readonly orgId: string;

  /**
   * Id of the invite to cancel
   */
  readonly inviteId: string;
}

/**
 * Request parameters for inviteMembersToOrganization operation in InvitesApi.
 */
export interface InvitesApiInviteMembersToOrganizationRequest {
  /**
   * Either the unique id of the organization, or the URL-friendly key of the organization (i.e: the \&quot;slug\&quot;).
   */
  readonly orgId: string;

  readonly inviteCreate: Array<InviteCreate>;

  readonly inviterName?: string;

  readonly inviterEmail?: string;
}

/**
 * Request parameters for listOrganizationInvites operation in InvitesApi.
 */
export interface InvitesApiListOrganizationInvitesRequest {
  /**
   * Either the unique id of the organization, or the URL-friendly key of the organization (i.e: the \&quot;slug\&quot;).
   */
  readonly orgId: string;

  /**
   * Page number of the results to fetch, starting at 1.
   */
  readonly page?: number;

  /**
   * The number of results per page (max 100).
   */
  readonly perPage?: number;
}

/**
 * InvitesApi - object-oriented interface
 */
export class InvitesApi extends BaseAPI {
  /**
   * Cancels an invite that was sent to a new member.
   * @summary Cancel Invite
   * @param {InvitesApiCancelInviteRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public cancelInvite(
    requestParameters: InvitesApiCancelInviteRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return InvitesApiFp(this.configuration)
      .cancelInvite(requestParameters.orgId, requestParameters.inviteId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Invite new members into the organization.
   * @summary Invite Members To Organization
   * @param {InvitesApiInviteMembersToOrganizationRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public inviteMembersToOrganization(
    requestParameters: InvitesApiInviteMembersToOrganizationRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return InvitesApiFp(this.configuration)
      .inviteMembersToOrganization(
        requestParameters.orgId,
        requestParameters.inviteCreate,
        requestParameters.inviterName,
        requestParameters.inviterEmail,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Lists pending organization invites
   * @summary List Organization Invites
   * @param {InvitesApiListOrganizationInvitesRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public listOrganizationInvites(
    requestParameters: InvitesApiListOrganizationInvitesRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return InvitesApiFp(this.configuration)
      .listOrganizationInvites(
        requestParameters.orgId,
        requestParameters.page,
        requestParameters.perPage,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
