/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { HTTPValidationError } from '../types';
// @ts-ignore
import { OrgMemberCreate } from '../types';
// @ts-ignore
import { OrgMemberReadWithGrants } from '../types';
// @ts-ignore
import { OrgMemberRemovePermissions } from '../types';
// @ts-ignore
import { OrgMemberUpdate } from '../types';
/**
 * MembersApi - axios parameter creator
 * @export
 */
export const MembersApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Create an organization member if needed, and grant it permissions.  The member can be specified either by ID (for an existing member), or by email (for either an existing member or a new one).  For a new member, an invite will be sent.
     * @summary Create Organization Members
     * @param {OrgMemberCreate} orgMemberCreate
     * @param {string} [inviterName]
     * @param {string} [inviterEmail]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createOrganizationMembers: async (
      orgMemberCreate: OrgMemberCreate,
      inviterName?: string,
      inviterEmail?: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'orgMemberCreate' is not null or undefined
      assertParamExists('createOrganizationMembers', 'orgMemberCreate', orgMemberCreate);
      const localVarPath = `/v2/members`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (inviterName !== undefined) {
        localVarQueryParameter['inviter_name'] = inviterName;
      }

      if (inviterEmail !== undefined) {
        localVarQueryParameter['inviter_email'] = inviterEmail;
      }

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        orgMemberCreate,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Deletes an account member matching the given id or email address. The member will be removed from the active account in permit.io.  If the member is the only member in its account (organization), returns 400 (bad request), due to nobody remains with access to the account, meaning deletion of the entire account (org). To completely remove an account, call DELETE `/orgs/{org}`.
     * @summary Delete Organization Member
     * @param {string} memberId Either the unique id (UUID) of the account member, or the email address of the account member.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteOrganizationMember: async (
      memberId: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'memberId' is not null or undefined
      assertParamExists('deleteOrganizationMember', 'memberId', memberId);
      const localVarPath = `/v2/members/{member_id}`.replace(
        `{${'member_id'}}`,
        encodeURIComponent(String(memberId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Remove permissions from a member. If the last permissions a member has are removed, the member is also deleted.
     * @summary Delete Organization Permissions
     * @param {OrgMemberRemovePermissions} orgMemberRemovePermissions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteOrganizationPermissions: async (
      orgMemberRemovePermissions: OrgMemberRemovePermissions,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'orgMemberRemovePermissions' is not null or undefined
      assertParamExists(
        'deleteOrganizationPermissions',
        'orgMemberRemovePermissions',
        orgMemberRemovePermissions,
      );
      const localVarPath = `/v2/members`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        orgMemberRemovePermissions,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Gets the authenticated account member\'s details.
     * @summary Get the authenticated account member
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAuthenticatedMember: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/v2/members/me`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Gets a single account member by its id or email address. matching the given member, if no such member exists under the current active account (organization), returns 404.
     * @summary Get Organization Member
     * @param {string} memberId Either the unique id (UUID) of the account member, or the email address of the account member.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOrganizationMember: async (
      memberId: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'memberId' is not null or undefined
      assertParamExists('getOrganizationMember', 'memberId', memberId);
      const localVarPath = `/v2/members/{member_id}`.replace(
        `{${'member_id'}}`,
        encodeURIComponent(String(memberId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Lists all the account members that current active account has access to, optionally filtering by project or environment. The active account/organization is determined by the API Key used or by the authenticated session id.
     * @summary List Organization Members
     * @param {string} [projectId]
     * @param {string} [envId]
     * @param {number} [page] Page number of the results to fetch, starting at 1.
     * @param {number} [perPage] The number of results per page (max 100).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listOrganizationMembers: async (
      projectId?: string,
      envId?: string,
      page?: number,
      perPage?: number,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/v2/members`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (projectId !== undefined) {
        localVarQueryParameter['project_id'] = projectId;
      }

      if (envId !== undefined) {
        localVarQueryParameter['env_id'] = envId;
      }

      if (page !== undefined) {
        localVarQueryParameter['page'] = page;
      }

      if (perPage !== undefined) {
        localVarQueryParameter['per_page'] = perPage;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Updates an account member\'s settings.
     * @summary Update Organization Member
     * @param {string} memberId Either the unique id (UUID) of the account member, or the email address of the account member.
     * @param {OrgMemberUpdate} orgMemberUpdate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateOrganizationMember: async (
      memberId: string,
      orgMemberUpdate: OrgMemberUpdate,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'memberId' is not null or undefined
      assertParamExists('updateOrganizationMember', 'memberId', memberId);
      // verify required parameter 'orgMemberUpdate' is not null or undefined
      assertParamExists('updateOrganizationMember', 'orgMemberUpdate', orgMemberUpdate);
      const localVarPath = `/v2/members/{member_id}`.replace(
        `{${'member_id'}}`,
        encodeURIComponent(String(memberId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        orgMemberUpdate,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * MembersApi - functional programming interface
 * @export
 */
export const MembersApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = MembersApiAxiosParamCreator(configuration);
  return {
    /**
     * Create an organization member if needed, and grant it permissions.  The member can be specified either by ID (for an existing member), or by email (for either an existing member or a new one).  For a new member, an invite will be sent.
     * @summary Create Organization Members
     * @param {OrgMemberCreate} orgMemberCreate
     * @param {string} [inviterName]
     * @param {string} [inviterEmail]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createOrganizationMembers(
      orgMemberCreate: OrgMemberCreate,
      inviterName?: string,
      inviterEmail?: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrgMemberReadWithGrants>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createOrganizationMembers(
        orgMemberCreate,
        inviterName,
        inviterEmail,
        options,
      );
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     * Deletes an account member matching the given id or email address. The member will be removed from the active account in permit.io.  If the member is the only member in its account (organization), returns 400 (bad request), due to nobody remains with access to the account, meaning deletion of the entire account (org). To completely remove an account, call DELETE `/orgs/{org}`.
     * @summary Delete Organization Member
     * @param {string} memberId Either the unique id (UUID) of the account member, or the email address of the account member.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteOrganizationMember(
      memberId: string,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteOrganizationMember(
        memberId,
        options,
      );
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     * Remove permissions from a member. If the last permissions a member has are removed, the member is also deleted.
     * @summary Delete Organization Permissions
     * @param {OrgMemberRemovePermissions} orgMemberRemovePermissions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteOrganizationPermissions(
      orgMemberRemovePermissions: OrgMemberRemovePermissions,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteOrganizationPermissions(
        orgMemberRemovePermissions,
        options,
      );
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     * Gets the authenticated account member\'s details.
     * @summary Get the authenticated account member
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getAuthenticatedMember(
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrgMemberReadWithGrants>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getAuthenticatedMember(options);
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     * Gets a single account member by its id or email address. matching the given member, if no such member exists under the current active account (organization), returns 404.
     * @summary Get Organization Member
     * @param {string} memberId Either the unique id (UUID) of the account member, or the email address of the account member.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getOrganizationMember(
      memberId: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrgMemberReadWithGrants>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getOrganizationMember(
        memberId,
        options,
      );
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     * Lists all the account members that current active account has access to, optionally filtering by project or environment. The active account/organization is determined by the API Key used or by the authenticated session id.
     * @summary List Organization Members
     * @param {string} [projectId]
     * @param {string} [envId]
     * @param {number} [page] Page number of the results to fetch, starting at 1.
     * @param {number} [perPage] The number of results per page (max 100).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listOrganizationMembers(
      projectId?: string,
      envId?: string,
      page?: number,
      perPage?: number,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<OrgMemberReadWithGrants>>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.listOrganizationMembers(
        projectId,
        envId,
        page,
        perPage,
        options,
      );
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
    /**
     * Updates an account member\'s settings.
     * @summary Update Organization Member
     * @param {string} memberId Either the unique id (UUID) of the account member, or the email address of the account member.
     * @param {OrgMemberUpdate} orgMemberUpdate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateOrganizationMember(
      memberId: string,
      orgMemberUpdate: OrgMemberUpdate,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrgMemberReadWithGrants>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateOrganizationMember(
        memberId,
        orgMemberUpdate,
        options,
      );
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
    },
  };
};

/**
 * MembersApi - factory interface
 * @export
 */
export const MembersApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = MembersApiFp(configuration);
  return {
    /**
     * Create an organization member if needed, and grant it permissions.  The member can be specified either by ID (for an existing member), or by email (for either an existing member or a new one).  For a new member, an invite will be sent.
     * @summary Create Organization Members
     * @param {OrgMemberCreate} orgMemberCreate
     * @param {string} [inviterName]
     * @param {string} [inviterEmail]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createOrganizationMembers(
      orgMemberCreate: OrgMemberCreate,
      inviterName?: string,
      inviterEmail?: string,
      options?: any,
    ): AxiosPromise<OrgMemberReadWithGrants> {
      return localVarFp
        .createOrganizationMembers(orgMemberCreate, inviterName, inviterEmail, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Deletes an account member matching the given id or email address. The member will be removed from the active account in permit.io.  If the member is the only member in its account (organization), returns 400 (bad request), due to nobody remains with access to the account, meaning deletion of the entire account (org). To completely remove an account, call DELETE `/orgs/{org}`.
     * @summary Delete Organization Member
     * @param {string} memberId Either the unique id (UUID) of the account member, or the email address of the account member.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteOrganizationMember(memberId: string, options?: any): AxiosPromise<void> {
      return localVarFp
        .deleteOrganizationMember(memberId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Remove permissions from a member. If the last permissions a member has are removed, the member is also deleted.
     * @summary Delete Organization Permissions
     * @param {OrgMemberRemovePermissions} orgMemberRemovePermissions
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteOrganizationPermissions(
      orgMemberRemovePermissions: OrgMemberRemovePermissions,
      options?: any,
    ): AxiosPromise<void> {
      return localVarFp
        .deleteOrganizationPermissions(orgMemberRemovePermissions, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Gets the authenticated account member\'s details.
     * @summary Get the authenticated account member
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAuthenticatedMember(options?: any): AxiosPromise<OrgMemberReadWithGrants> {
      return localVarFp.getAuthenticatedMember(options).then((request) => request(axios, basePath));
    },
    /**
     * Gets a single account member by its id or email address. matching the given member, if no such member exists under the current active account (organization), returns 404.
     * @summary Get Organization Member
     * @param {string} memberId Either the unique id (UUID) of the account member, or the email address of the account member.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOrganizationMember(memberId: string, options?: any): AxiosPromise<OrgMemberReadWithGrants> {
      return localVarFp
        .getOrganizationMember(memberId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Lists all the account members that current active account has access to, optionally filtering by project or environment. The active account/organization is determined by the API Key used or by the authenticated session id.
     * @summary List Organization Members
     * @param {string} [projectId]
     * @param {string} [envId]
     * @param {number} [page] Page number of the results to fetch, starting at 1.
     * @param {number} [perPage] The number of results per page (max 100).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listOrganizationMembers(
      projectId?: string,
      envId?: string,
      page?: number,
      perPage?: number,
      options?: any,
    ): AxiosPromise<Array<OrgMemberReadWithGrants>> {
      return localVarFp
        .listOrganizationMembers(projectId, envId, page, perPage, options)
        .then((request) => request(axios, basePath));
    },
    /**
     * Updates an account member\'s settings.
     * @summary Update Organization Member
     * @param {string} memberId Either the unique id (UUID) of the account member, or the email address of the account member.
     * @param {OrgMemberUpdate} orgMemberUpdate
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateOrganizationMember(
      memberId: string,
      orgMemberUpdate: OrgMemberUpdate,
      options?: any,
    ): AxiosPromise<OrgMemberReadWithGrants> {
      return localVarFp
        .updateOrganizationMember(memberId, orgMemberUpdate, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for createOrganizationMembers operation in MembersApi.
 * @export
 * @interface MembersApiCreateOrganizationMembersRequest
 */
export interface MembersApiCreateOrganizationMembersRequest {
  /**
   *
   * @type {OrgMemberCreate}
   * @memberof MembersApiCreateOrganizationMembers
   */
  readonly orgMemberCreate: OrgMemberCreate;

  /**
   *
   * @type {string}
   * @memberof MembersApiCreateOrganizationMembers
   */
  readonly inviterName?: string;

  /**
   *
   * @type {string}
   * @memberof MembersApiCreateOrganizationMembers
   */
  readonly inviterEmail?: string;
}

/**
 * Request parameters for deleteOrganizationMember operation in MembersApi.
 * @export
 * @interface MembersApiDeleteOrganizationMemberRequest
 */
export interface MembersApiDeleteOrganizationMemberRequest {
  /**
   * Either the unique id (UUID) of the account member, or the email address of the account member.
   * @type {string}
   * @memberof MembersApiDeleteOrganizationMember
   */
  readonly memberId: string;
}

/**
 * Request parameters for deleteOrganizationPermissions operation in MembersApi.
 * @export
 * @interface MembersApiDeleteOrganizationPermissionsRequest
 */
export interface MembersApiDeleteOrganizationPermissionsRequest {
  /**
   *
   * @type {OrgMemberRemovePermissions}
   * @memberof MembersApiDeleteOrganizationPermissions
   */
  readonly orgMemberRemovePermissions: OrgMemberRemovePermissions;
}

/**
 * Request parameters for getOrganizationMember operation in MembersApi.
 * @export
 * @interface MembersApiGetOrganizationMemberRequest
 */
export interface MembersApiGetOrganizationMemberRequest {
  /**
   * Either the unique id (UUID) of the account member, or the email address of the account member.
   * @type {string}
   * @memberof MembersApiGetOrganizationMember
   */
  readonly memberId: string;
}

/**
 * Request parameters for listOrganizationMembers operation in MembersApi.
 * @export
 * @interface MembersApiListOrganizationMembersRequest
 */
export interface MembersApiListOrganizationMembersRequest {
  /**
   *
   * @type {string}
   * @memberof MembersApiListOrganizationMembers
   */
  readonly projectId?: string;

  /**
   *
   * @type {string}
   * @memberof MembersApiListOrganizationMembers
   */
  readonly envId?: string;

  /**
   * Page number of the results to fetch, starting at 1.
   * @type {number}
   * @memberof MembersApiListOrganizationMembers
   */
  readonly page?: number;

  /**
   * The number of results per page (max 100).
   * @type {number}
   * @memberof MembersApiListOrganizationMembers
   */
  readonly perPage?: number;
}

/**
 * Request parameters for updateOrganizationMember operation in MembersApi.
 * @export
 * @interface MembersApiUpdateOrganizationMemberRequest
 */
export interface MembersApiUpdateOrganizationMemberRequest {
  /**
   * Either the unique id (UUID) of the account member, or the email address of the account member.
   * @type {string}
   * @memberof MembersApiUpdateOrganizationMember
   */
  readonly memberId: string;

  /**
   *
   * @type {OrgMemberUpdate}
   * @memberof MembersApiUpdateOrganizationMember
   */
  readonly orgMemberUpdate: OrgMemberUpdate;
}

/**
 * MembersApi - object-oriented interface
 * @export
 * @class MembersApi
 * @extends {BaseAPI}
 */
export class MembersApi extends BaseAPI {
  /**
   * Create an organization member if needed, and grant it permissions.  The member can be specified either by ID (for an existing member), or by email (for either an existing member or a new one).  For a new member, an invite will be sent.
   * @summary Create Organization Members
   * @param {MembersApiCreateOrganizationMembersRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof MembersApi
   */
  public createOrganizationMembers(
    requestParameters: MembersApiCreateOrganizationMembersRequest,
    options?: AxiosRequestConfig,
  ) {
    return MembersApiFp(this.configuration)
      .createOrganizationMembers(
        requestParameters.orgMemberCreate,
        requestParameters.inviterName,
        requestParameters.inviterEmail,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Deletes an account member matching the given id or email address. The member will be removed from the active account in permit.io.  If the member is the only member in its account (organization), returns 400 (bad request), due to nobody remains with access to the account, meaning deletion of the entire account (org). To completely remove an account, call DELETE `/orgs/{org}`.
   * @summary Delete Organization Member
   * @param {MembersApiDeleteOrganizationMemberRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof MembersApi
   */
  public deleteOrganizationMember(
    requestParameters: MembersApiDeleteOrganizationMemberRequest,
    options?: AxiosRequestConfig,
  ) {
    return MembersApiFp(this.configuration)
      .deleteOrganizationMember(requestParameters.memberId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Remove permissions from a member. If the last permissions a member has are removed, the member is also deleted.
   * @summary Delete Organization Permissions
   * @param {MembersApiDeleteOrganizationPermissionsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof MembersApi
   */
  public deleteOrganizationPermissions(
    requestParameters: MembersApiDeleteOrganizationPermissionsRequest,
    options?: AxiosRequestConfig,
  ) {
    return MembersApiFp(this.configuration)
      .deleteOrganizationPermissions(requestParameters.orgMemberRemovePermissions, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Gets the authenticated account member\'s details.
   * @summary Get the authenticated account member
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof MembersApi
   */
  public getAuthenticatedMember(options?: AxiosRequestConfig) {
    return MembersApiFp(this.configuration)
      .getAuthenticatedMember(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Gets a single account member by its id or email address. matching the given member, if no such member exists under the current active account (organization), returns 404.
   * @summary Get Organization Member
   * @param {MembersApiGetOrganizationMemberRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof MembersApi
   */
  public getOrganizationMember(
    requestParameters: MembersApiGetOrganizationMemberRequest,
    options?: AxiosRequestConfig,
  ) {
    return MembersApiFp(this.configuration)
      .getOrganizationMember(requestParameters.memberId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Lists all the account members that current active account has access to, optionally filtering by project or environment. The active account/organization is determined by the API Key used or by the authenticated session id.
   * @summary List Organization Members
   * @param {MembersApiListOrganizationMembersRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof MembersApi
   */
  public listOrganizationMembers(
    requestParameters: MembersApiListOrganizationMembersRequest = {},
    options?: AxiosRequestConfig,
  ) {
    return MembersApiFp(this.configuration)
      .listOrganizationMembers(
        requestParameters.projectId,
        requestParameters.envId,
        requestParameters.page,
        requestParameters.perPage,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Updates an account member\'s settings.
   * @summary Update Organization Member
   * @param {MembersApiUpdateOrganizationMemberRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof MembersApi
   */
  public updateOrganizationMember(
    requestParameters: MembersApiUpdateOrganizationMemberRequest,
    options?: AxiosRequestConfig,
  ) {
    return MembersApiFp(this.configuration)
      .updateOrganizationMember(
        requestParameters.memberId,
        requestParameters.orgMemberUpdate,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
