/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AxiosInstance, AxiosPromise, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
import { BASE_PATH, BaseAPI, operationServerMap, type RequestArgs } from '../base';
import {
  DUMMY_BASE_URL,
  assertParamExists,
  createRequestFunction,
  serializeDataIfNeeded,
  setBearerAuthToObject,
  setSearchParams,
  toPathString,
} from '../common';
import type { Configuration } from '../configuration';
import type { PaginatedResultRelationRead, RelationCreate, RelationRead } from '../types';
/**
 * ResourceRelationsApi - axios parameter creator
 */
export const ResourceRelationsApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Creates a resource relation to another resource
     * @summary Create Resource Relation
     * @param {string} resourceId Either the unique id of the resource, or the URL-friendly key of the resource (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {RelationCreate} relationCreate
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    createResourceRelation: async (
      resourceId: string,
      projId: string,
      envId: string,
      relationCreate: RelationCreate,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'resourceId' is not null or undefined
      assertParamExists('createResourceRelation', 'resourceId', resourceId);
      // verify required parameter 'projId' is not null or undefined
      assertParamExists('createResourceRelation', 'projId', projId);
      // verify required parameter 'envId' is not null or undefined
      assertParamExists('createResourceRelation', 'envId', envId);
      // verify required parameter 'relationCreate' is not null or undefined
      assertParamExists('createResourceRelation', 'relationCreate', relationCreate);
      const localVarPath = `/v2/schema/{proj_id}/{env_id}/resources/{resource_id}/relations`
        .replace('{resource_id}', encodeURIComponent(String(resourceId)))
        .replace('{proj_id}', encodeURIComponent(String(projId)))
        .replace('{env_id}', encodeURIComponent(String(envId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';
      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        relationCreate,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Deletes a resource relation
     * @summary Delete Resource Relation
     * @param {string} resourceId Either the unique id of the resource, or the URL-friendly key of the resource (i.e: the \&quot;slug\&quot;).
     * @param {string} relationId Either the unique id of the relation, or the URL-friendly key of the relation (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    deleteResourceRelation: async (
      resourceId: string,
      relationId: string,
      projId: string,
      envId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'resourceId' is not null or undefined
      assertParamExists('deleteResourceRelation', 'resourceId', resourceId);
      // verify required parameter 'relationId' is not null or undefined
      assertParamExists('deleteResourceRelation', 'relationId', relationId);
      // verify required parameter 'projId' is not null or undefined
      assertParamExists('deleteResourceRelation', 'projId', projId);
      // verify required parameter 'envId' is not null or undefined
      assertParamExists('deleteResourceRelation', 'envId', envId);
      const localVarPath =
        `/v2/schema/{proj_id}/{env_id}/resources/{resource_id}/relations/{relation_id}`
          .replace('{resource_id}', encodeURIComponent(String(resourceId)))
          .replace('{relation_id}', encodeURIComponent(String(relationId)))
          .replace('{proj_id}', encodeURIComponent(String(projId)))
          .replace('{env_id}', encodeURIComponent(String(envId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Get a resource relation
     * @summary Get Resource Relation
     * @param {string} resourceId Either the unique id of the resource, or the URL-friendly key of the resource (i.e: the \&quot;slug\&quot;).
     * @param {string} relationId Either the unique id of the relation, or the URL-friendly key of the relation (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    getResourceRelation: async (
      resourceId: string,
      relationId: string,
      projId: string,
      envId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'resourceId' is not null or undefined
      assertParamExists('getResourceRelation', 'resourceId', resourceId);
      // verify required parameter 'relationId' is not null or undefined
      assertParamExists('getResourceRelation', 'relationId', relationId);
      // verify required parameter 'projId' is not null or undefined
      assertParamExists('getResourceRelation', 'projId', projId);
      // verify required parameter 'envId' is not null or undefined
      assertParamExists('getResourceRelation', 'envId', envId);
      const localVarPath =
        `/v2/schema/{proj_id}/{env_id}/resources/{resource_id}/relations/{relation_id}`
          .replace('{resource_id}', encodeURIComponent(String(resourceId)))
          .replace('{relation_id}', encodeURIComponent(String(relationId)))
          .replace('{proj_id}', encodeURIComponent(String(projId)))
          .replace('{env_id}', encodeURIComponent(String(envId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * List relations on a given resource
     * @summary List Resource Relations
     * @param {string} resourceId Either the unique id of the resource, or the URL-friendly key of the resource (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {number} [page] Page number of the results to fetch, starting at 1.
     * @param {number} [perPage] The number of results per page (max 100).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    listResourceRelations: async (
      resourceId: string,
      projId: string,
      envId: string,
      page?: number,
      perPage?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'resourceId' is not null or undefined
      assertParamExists('listResourceRelations', 'resourceId', resourceId);
      // verify required parameter 'projId' is not null or undefined
      assertParamExists('listResourceRelations', 'projId', projId);
      // verify required parameter 'envId' is not null or undefined
      assertParamExists('listResourceRelations', 'envId', envId);
      const localVarPath = `/v2/schema/{proj_id}/{env_id}/resources/{resource_id}/relations`
        .replace('{resource_id}', encodeURIComponent(String(resourceId)))
        .replace('{proj_id}', encodeURIComponent(String(projId)))
        .replace('{env_id}', encodeURIComponent(String(envId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (page !== undefined) {
        localVarQueryParameter['page'] = page;
      }

      if (perPage !== undefined) {
        localVarQueryParameter['per_page'] = perPage;
      }

      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ResourceRelationsApi - functional programming interface
 */
export const ResourceRelationsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = ResourceRelationsApiAxiosParamCreator(configuration);
  return {
    /**
     * Creates a resource relation to another resource
     * @summary Create Resource Relation
     * @param {string} resourceId Either the unique id of the resource, or the URL-friendly key of the resource (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {RelationCreate} relationCreate
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async createResourceRelation(
      resourceId: string,
      projId: string,
      envId: string,
      relationCreate: RelationCreate,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RelationRead>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createResourceRelation(
        resourceId,
        projId,
        envId,
        relationCreate,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ResourceRelationsApi.createResourceRelation']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Deletes a resource relation
     * @summary Delete Resource Relation
     * @param {string} resourceId Either the unique id of the resource, or the URL-friendly key of the resource (i.e: the \&quot;slug\&quot;).
     * @param {string} relationId Either the unique id of the relation, or the URL-friendly key of the relation (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async deleteResourceRelation(
      resourceId: string,
      relationId: string,
      projId: string,
      envId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteResourceRelation(
        resourceId,
        relationId,
        projId,
        envId,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ResourceRelationsApi.deleteResourceRelation']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Get a resource relation
     * @summary Get Resource Relation
     * @param {string} resourceId Either the unique id of the resource, or the URL-friendly key of the resource (i.e: the \&quot;slug\&quot;).
     * @param {string} relationId Either the unique id of the relation, or the URL-friendly key of the relation (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async getResourceRelation(
      resourceId: string,
      relationId: string,
      projId: string,
      envId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RelationRead>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getResourceRelation(
        resourceId,
        relationId,
        projId,
        envId,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ResourceRelationsApi.getResourceRelation']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * List relations on a given resource
     * @summary List Resource Relations
     * @param {string} resourceId Either the unique id of the resource, or the URL-friendly key of the resource (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {number} [page] Page number of the results to fetch, starting at 1.
     * @param {number} [perPage] The number of results per page (max 100).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async listResourceRelations(
      resourceId: string,
      projId: string,
      envId: string,
      page?: number,
      perPage?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedResultRelationRead>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.listResourceRelations(
        resourceId,
        projId,
        envId,
        page,
        perPage,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['ResourceRelationsApi.listResourceRelations']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * ResourceRelationsApi - factory interface
 */
export const ResourceRelationsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = ResourceRelationsApiFp(configuration);
  return {
    /**
     * Creates a resource relation to another resource
     * @summary Create Resource Relation
     * @param {ResourceRelationsApiCreateResourceRelationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    createResourceRelation(
      requestParameters: ResourceRelationsApiCreateResourceRelationRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<RelationRead> {
      return localVarFp
        .createResourceRelation(
          requestParameters.resourceId,
          requestParameters.projId,
          requestParameters.envId,
          requestParameters.relationCreate,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Deletes a resource relation
     * @summary Delete Resource Relation
     * @param {ResourceRelationsApiDeleteResourceRelationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    deleteResourceRelation(
      requestParameters: ResourceRelationsApiDeleteResourceRelationRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .deleteResourceRelation(
          requestParameters.resourceId,
          requestParameters.relationId,
          requestParameters.projId,
          requestParameters.envId,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Get a resource relation
     * @summary Get Resource Relation
     * @param {ResourceRelationsApiGetResourceRelationRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    getResourceRelation(
      requestParameters: ResourceRelationsApiGetResourceRelationRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<RelationRead> {
      return localVarFp
        .getResourceRelation(
          requestParameters.resourceId,
          requestParameters.relationId,
          requestParameters.projId,
          requestParameters.envId,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * List relations on a given resource
     * @summary List Resource Relations
     * @param {ResourceRelationsApiListResourceRelationsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    listResourceRelations(
      requestParameters: ResourceRelationsApiListResourceRelationsRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PaginatedResultRelationRead> {
      return localVarFp
        .listResourceRelations(
          requestParameters.resourceId,
          requestParameters.projId,
          requestParameters.envId,
          requestParameters.page,
          requestParameters.perPage,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for createResourceRelation operation in ResourceRelationsApi.
 */
export interface ResourceRelationsApiCreateResourceRelationRequest {
  /**
   * Either the unique id of the resource, or the URL-friendly key of the resource (i.e: the \&quot;slug\&quot;).
   */
  readonly resourceId: string;

  /**
   * Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
   */
  readonly projId: string;

  /**
   * Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
   */
  readonly envId: string;

  readonly relationCreate: RelationCreate;
}

/**
 * Request parameters for deleteResourceRelation operation in ResourceRelationsApi.
 */
export interface ResourceRelationsApiDeleteResourceRelationRequest {
  /**
   * Either the unique id of the resource, or the URL-friendly key of the resource (i.e: the \&quot;slug\&quot;).
   */
  readonly resourceId: string;

  /**
   * Either the unique id of the relation, or the URL-friendly key of the relation (i.e: the \&quot;slug\&quot;).
   */
  readonly relationId: string;

  /**
   * Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
   */
  readonly projId: string;

  /**
   * Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
   */
  readonly envId: string;
}

/**
 * Request parameters for getResourceRelation operation in ResourceRelationsApi.
 */
export interface ResourceRelationsApiGetResourceRelationRequest {
  /**
   * Either the unique id of the resource, or the URL-friendly key of the resource (i.e: the \&quot;slug\&quot;).
   */
  readonly resourceId: string;

  /**
   * Either the unique id of the relation, or the URL-friendly key of the relation (i.e: the \&quot;slug\&quot;).
   */
  readonly relationId: string;

  /**
   * Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
   */
  readonly projId: string;

  /**
   * Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
   */
  readonly envId: string;
}

/**
 * Request parameters for listResourceRelations operation in ResourceRelationsApi.
 */
export interface ResourceRelationsApiListResourceRelationsRequest {
  /**
   * Either the unique id of the resource, or the URL-friendly key of the resource (i.e: the \&quot;slug\&quot;).
   */
  readonly resourceId: string;

  /**
   * Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
   */
  readonly projId: string;

  /**
   * Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
   */
  readonly envId: string;

  /**
   * Page number of the results to fetch, starting at 1.
   */
  readonly page?: number;

  /**
   * The number of results per page (max 100).
   */
  readonly perPage?: number;
}

/**
 * ResourceRelationsApi - object-oriented interface
 */
export class ResourceRelationsApi extends BaseAPI {
  /**
   * Creates a resource relation to another resource
   * @summary Create Resource Relation
   * @param {ResourceRelationsApiCreateResourceRelationRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public createResourceRelation(
    requestParameters: ResourceRelationsApiCreateResourceRelationRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ResourceRelationsApiFp(this.configuration)
      .createResourceRelation(
        requestParameters.resourceId,
        requestParameters.projId,
        requestParameters.envId,
        requestParameters.relationCreate,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Deletes a resource relation
   * @summary Delete Resource Relation
   * @param {ResourceRelationsApiDeleteResourceRelationRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public deleteResourceRelation(
    requestParameters: ResourceRelationsApiDeleteResourceRelationRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ResourceRelationsApiFp(this.configuration)
      .deleteResourceRelation(
        requestParameters.resourceId,
        requestParameters.relationId,
        requestParameters.projId,
        requestParameters.envId,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Get a resource relation
   * @summary Get Resource Relation
   * @param {ResourceRelationsApiGetResourceRelationRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public getResourceRelation(
    requestParameters: ResourceRelationsApiGetResourceRelationRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ResourceRelationsApiFp(this.configuration)
      .getResourceRelation(
        requestParameters.resourceId,
        requestParameters.relationId,
        requestParameters.projId,
        requestParameters.envId,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * List relations on a given resource
   * @summary List Resource Relations
   * @param {ResourceRelationsApiListResourceRelationsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public listResourceRelations(
    requestParameters: ResourceRelationsApiListResourceRelationsRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return ResourceRelationsApiFp(this.configuration)
      .listResourceRelations(
        requestParameters.resourceId,
        requestParameters.projId,
        requestParameters.envId,
        requestParameters.page,
        requestParameters.perPage,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
