/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AxiosInstance, AxiosPromise, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
import { BASE_PATH, BaseAPI, operationServerMap, type RequestArgs } from '../base';
import {
  DUMMY_BASE_URL,
  assertParamExists,
  createRequestFunction,
  serializeDataIfNeeded,
  setBearerAuthToObject,
  setSearchParams,
  toPathString,
} from '../common';
import type { Configuration } from '../configuration';
import type {
  PaginatedResultUserRead,
  RoleAssignmentRead,
  SearchOperator,
  UserCreate,
  UserRead,
  UserRoleCreate,
  UserRoleRemove,
  UserUpdate,
} from '../types';
/**
 * UsersApi - axios parameter creator
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Assigns a role to the user within the tenant.  The tenant defines the scope of the assignment. In other words, the role is effective only within the tenant.
     * @summary Assign Role To User
     * @param {string} userId Either the unique id of the user, or the URL-friendly key of the user (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {UserRoleCreate} userRoleCreate
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    assignRoleToUser: async (
      userId: string,
      projId: string,
      envId: string,
      userRoleCreate: UserRoleCreate,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'userId' is not null or undefined
      assertParamExists('assignRoleToUser', 'userId', userId);
      // verify required parameter 'projId' is not null or undefined
      assertParamExists('assignRoleToUser', 'projId', projId);
      // verify required parameter 'envId' is not null or undefined
      assertParamExists('assignRoleToUser', 'envId', envId);
      // verify required parameter 'userRoleCreate' is not null or undefined
      assertParamExists('assignRoleToUser', 'userRoleCreate', userRoleCreate);
      const localVarPath = `/v2/facts/{proj_id}/{env_id}/users/{user_id}/roles`
        .replace('{user_id}', encodeURIComponent(String(userId)))
        .replace('{proj_id}', encodeURIComponent(String(projId)))
        .replace('{env_id}', encodeURIComponent(String(envId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';
      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        userRoleCreate,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Creates a new user inside the Permit.io system, from that point forward you may run permission checks on that user.  Returns 201 if the user is created, 409 if the user already exists or if an inline role assignment names a tenant other than the one its resource instance already exists in. User is identified by its key, and you can only create one user with the same key inside a Permit environment.
     * @summary Create User
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {UserCreate} userCreate
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    createUser: async (
      projId: string,
      envId: string,
      userCreate: UserCreate,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'projId' is not null or undefined
      assertParamExists('createUser', 'projId', projId);
      // verify required parameter 'envId' is not null or undefined
      assertParamExists('createUser', 'envId', envId);
      // verify required parameter 'userCreate' is not null or undefined
      assertParamExists('createUser', 'userCreate', userCreate);
      const localVarPath = `/v2/facts/{proj_id}/{env_id}/users`
        .replace('{proj_id}', encodeURIComponent(String(projId)))
        .replace('{env_id}', encodeURIComponent(String(envId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';
      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        userCreate,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Deletes the user and all its related data.
     * @summary Delete User
     * @param {string} userId Either the unique id of the user, or the URL-friendly key of the user (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    deleteUser: async (
      userId: string,
      projId: string,
      envId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'userId' is not null or undefined
      assertParamExists('deleteUser', 'userId', userId);
      // verify required parameter 'projId' is not null or undefined
      assertParamExists('deleteUser', 'projId', projId);
      // verify required parameter 'envId' is not null or undefined
      assertParamExists('deleteUser', 'envId', envId);
      const localVarPath = `/v2/facts/{proj_id}/{env_id}/users/{user_id}`
        .replace('{user_id}', encodeURIComponent(String(userId)))
        .replace('{proj_id}', encodeURIComponent(String(projId)))
        .replace('{env_id}', encodeURIComponent(String(envId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Gets a user, if such user exists. Otherwise returns 404.
     * @summary Get User
     * @param {string} userId Either the unique id of the user, or the URL-friendly key of the user (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    getUser: async (
      userId: string,
      projId: string,
      envId: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'userId' is not null or undefined
      assertParamExists('getUser', 'userId', userId);
      // verify required parameter 'projId' is not null or undefined
      assertParamExists('getUser', 'projId', projId);
      // verify required parameter 'envId' is not null or undefined
      assertParamExists('getUser', 'envId', envId);
      const localVarPath = `/v2/facts/{proj_id}/{env_id}/users/{user_id}`
        .replace('{user_id}', encodeURIComponent(String(userId)))
        .replace('{proj_id}', encodeURIComponent(String(projId)))
        .replace('{env_id}', encodeURIComponent(String(envId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Lists all the users defined within an environment.
     * @summary List Users
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {string} [search] Text search for the user
     * @param {SearchOperator} [searchOperator] The search operator to use. &#x60;contains&#x60; performs a substring match on email, key, first_name, and last_name. &#x60;startswith&#x60; performs a prefix match on email, key, first_name, and last_name.
     * @param {string} [role] Match users with a specific role. To filter users without any roles, send an empty string.
     * @param {boolean} [includeResourceInstanceRoles] Should add resource instance roles
     * @param {number} [page] Page number of the results to fetch, starting at 1.
     * @param {number} [perPage] The number of results per page (max 100).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    listUsers: async (
      projId: string,
      envId: string,
      search?: string,
      searchOperator?: SearchOperator,
      role?: string,
      includeResourceInstanceRoles?: boolean,
      page?: number,
      perPage?: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'projId' is not null or undefined
      assertParamExists('listUsers', 'projId', projId);
      // verify required parameter 'envId' is not null or undefined
      assertParamExists('listUsers', 'envId', envId);
      const localVarPath = `/v2/facts/{proj_id}/{env_id}/users`
        .replace('{proj_id}', encodeURIComponent(String(projId)))
        .replace('{env_id}', encodeURIComponent(String(envId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (search !== undefined) {
        localVarQueryParameter['search'] = search;
      }

      if (searchOperator !== undefined) {
        localVarQueryParameter['search_operator'] = searchOperator;
      }

      if (role !== undefined) {
        localVarQueryParameter['role'] = role;
      }

      if (includeResourceInstanceRoles !== undefined) {
        localVarQueryParameter['include_resource_instance_roles'] = includeResourceInstanceRoles;
      }

      if (page !== undefined) {
        localVarQueryParameter['page'] = page;
      }

      if (perPage !== undefined) {
        localVarQueryParameter['per_page'] = perPage;
      }

      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Replace User / Sync User upsert a user in the system. If the user already exists, it will update the user with the new data. If the user does not exist, it will create a new user with the provided data.  The user is identified by its key, and you can only create one user with the same key inside a Permit environment. A 200 status code will be returned if the user already exists, and a 201 status code will be returned if the user is created.
     * @summary Replace User
     * @param {string} userId Either the unique id of the user, or the URL-friendly key of the user (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {UserCreate} userCreate
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    replaceUser: async (
      userId: string,
      projId: string,
      envId: string,
      userCreate: UserCreate,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'userId' is not null or undefined
      assertParamExists('replaceUser', 'userId', userId);
      // verify required parameter 'projId' is not null or undefined
      assertParamExists('replaceUser', 'projId', projId);
      // verify required parameter 'envId' is not null or undefined
      assertParamExists('replaceUser', 'envId', envId);
      // verify required parameter 'userCreate' is not null or undefined
      assertParamExists('replaceUser', 'userCreate', userCreate);
      const localVarPath = `/v2/facts/{proj_id}/{env_id}/users/{user_id}`
        .replace('{user_id}', encodeURIComponent(String(userId)))
        .replace('{proj_id}', encodeURIComponent(String(projId)))
        .replace('{env_id}', encodeURIComponent(String(envId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';
      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        userCreate,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Unassigns the role from the user within the tenant.  The tenant defines the scope of the assignment. In other words, the role is effective only within the tenant.  If the role is not actually assigned, will return 404.
     * @summary Unassign Role From User
     * @param {string} userId Either the unique id of the user, or the URL-friendly key of the user (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {UserRoleRemove} userRoleRemove
     * @param {boolean} [returnDeleted] Whether to return the deleted role assignment, status code will be 200 instead of the default 204 if true
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    unassignRoleFromUser: async (
      userId: string,
      projId: string,
      envId: string,
      userRoleRemove: UserRoleRemove,
      returnDeleted?: boolean,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'userId' is not null or undefined
      assertParamExists('unassignRoleFromUser', 'userId', userId);
      // verify required parameter 'projId' is not null or undefined
      assertParamExists('unassignRoleFromUser', 'projId', projId);
      // verify required parameter 'envId' is not null or undefined
      assertParamExists('unassignRoleFromUser', 'envId', envId);
      // verify required parameter 'userRoleRemove' is not null or undefined
      assertParamExists('unassignRoleFromUser', 'userRoleRemove', userRoleRemove);
      const localVarPath = `/v2/facts/{proj_id}/{env_id}/users/{user_id}/roles`
        .replace('{user_id}', encodeURIComponent(String(userId)))
        .replace('{proj_id}', encodeURIComponent(String(projId)))
        .replace('{env_id}', encodeURIComponent(String(envId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      if (returnDeleted !== undefined) {
        localVarQueryParameter['return_deleted'] = returnDeleted;
      }

      localVarHeaderParameter['Content-Type'] = 'application/json';
      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        userRoleRemove,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     * Partially updates the user definition. Fields that will be provided will be completely overwritten.
     * @summary Update User
     * @param {string} userId Either the unique id of the user, or the URL-friendly key of the user (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {UserUpdate} userUpdate
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    updateUser: async (
      userId: string,
      projId: string,
      envId: string,
      userUpdate: UserUpdate,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'userId' is not null or undefined
      assertParamExists('updateUser', 'userId', userId);
      // verify required parameter 'projId' is not null or undefined
      assertParamExists('updateUser', 'projId', projId);
      // verify required parameter 'envId' is not null or undefined
      assertParamExists('updateUser', 'envId', envId);
      // verify required parameter 'userUpdate' is not null or undefined
      assertParamExists('updateUser', 'userUpdate', userUpdate);
      const localVarPath = `/v2/facts/{proj_id}/{env_id}/users/{user_id}`
        .replace('{user_id}', encodeURIComponent(String(userId)))
        .replace('{proj_id}', encodeURIComponent(String(projId)))
        .replace('{env_id}', encodeURIComponent(String(envId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      // authentication HTTPBearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration);

      localVarHeaderParameter['Content-Type'] = 'application/json';
      localVarHeaderParameter['Accept'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        userUpdate,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * UsersApi - functional programming interface
 */
export const UsersApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration);
  return {
    /**
     * Assigns a role to the user within the tenant.  The tenant defines the scope of the assignment. In other words, the role is effective only within the tenant.
     * @summary Assign Role To User
     * @param {string} userId Either the unique id of the user, or the URL-friendly key of the user (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {UserRoleCreate} userRoleCreate
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async assignRoleToUser(
      userId: string,
      projId: string,
      envId: string,
      userRoleCreate: UserRoleCreate,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RoleAssignmentRead>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.assignRoleToUser(
        userId,
        projId,
        envId,
        userRoleCreate,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['UsersApi.assignRoleToUser']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Creates a new user inside the Permit.io system, from that point forward you may run permission checks on that user.  Returns 201 if the user is created, 409 if the user already exists or if an inline role assignment names a tenant other than the one its resource instance already exists in. User is identified by its key, and you can only create one user with the same key inside a Permit environment.
     * @summary Create User
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {UserCreate} userCreate
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async createUser(
      projId: string,
      envId: string,
      userCreate: UserCreate,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserRead>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createUser(
        projId,
        envId,
        userCreate,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['UsersApi.createUser']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Deletes the user and all its related data.
     * @summary Delete User
     * @param {string} userId Either the unique id of the user, or the URL-friendly key of the user (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async deleteUser(
      userId: string,
      projId: string,
      envId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteUser(
        userId,
        projId,
        envId,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['UsersApi.deleteUser']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Gets a user, if such user exists. Otherwise returns 404.
     * @summary Get User
     * @param {string} userId Either the unique id of the user, or the URL-friendly key of the user (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async getUser(
      userId: string,
      projId: string,
      envId: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserRead>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getUser(
        userId,
        projId,
        envId,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['UsersApi.getUser']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Lists all the users defined within an environment.
     * @summary List Users
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {string} [search] Text search for the user
     * @param {SearchOperator} [searchOperator] The search operator to use. &#x60;contains&#x60; performs a substring match on email, key, first_name, and last_name. &#x60;startswith&#x60; performs a prefix match on email, key, first_name, and last_name.
     * @param {string} [role] Match users with a specific role. To filter users without any roles, send an empty string.
     * @param {boolean} [includeResourceInstanceRoles] Should add resource instance roles
     * @param {number} [page] Page number of the results to fetch, starting at 1.
     * @param {number} [perPage] The number of results per page (max 100).
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async listUsers(
      projId: string,
      envId: string,
      search?: string,
      searchOperator?: SearchOperator,
      role?: string,
      includeResourceInstanceRoles?: boolean,
      page?: number,
      perPage?: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedResultUserRead>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.listUsers(
        projId,
        envId,
        search,
        searchOperator,
        role,
        includeResourceInstanceRoles,
        page,
        perPage,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['UsersApi.listUsers']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Replace User / Sync User upsert a user in the system. If the user already exists, it will update the user with the new data. If the user does not exist, it will create a new user with the provided data.  The user is identified by its key, and you can only create one user with the same key inside a Permit environment. A 200 status code will be returned if the user already exists, and a 201 status code will be returned if the user is created.
     * @summary Replace User
     * @param {string} userId Either the unique id of the user, or the URL-friendly key of the user (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {UserCreate} userCreate
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async replaceUser(
      userId: string,
      projId: string,
      envId: string,
      userCreate: UserCreate,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserRead>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.replaceUser(
        userId,
        projId,
        envId,
        userCreate,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['UsersApi.replaceUser']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Unassigns the role from the user within the tenant.  The tenant defines the scope of the assignment. In other words, the role is effective only within the tenant.  If the role is not actually assigned, will return 404.
     * @summary Unassign Role From User
     * @param {string} userId Either the unique id of the user, or the URL-friendly key of the user (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {UserRoleRemove} userRoleRemove
     * @param {boolean} [returnDeleted] Whether to return the deleted role assignment, status code will be 200 instead of the default 204 if true
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async unassignRoleFromUser(
      userId: string,
      projId: string,
      envId: string,
      userRoleRemove: UserRoleRemove,
      returnDeleted?: boolean,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RoleAssignmentRead>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.unassignRoleFromUser(
        userId,
        projId,
        envId,
        userRoleRemove,
        returnDeleted,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['UsersApi.unassignRoleFromUser']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     * Partially updates the user definition. Fields that will be provided will be completely overwritten.
     * @summary Update User
     * @param {string} userId Either the unique id of the user, or the URL-friendly key of the user (i.e: the \&quot;slug\&quot;).
     * @param {string} projId Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
     * @param {string} envId Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
     * @param {UserUpdate} userUpdate
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    async updateUser(
      userId: string,
      projId: string,
      envId: string,
      userUpdate: UserUpdate,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserRead>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateUser(
        userId,
        projId,
        envId,
        userUpdate,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['UsersApi.updateUser']?.[localVarOperationServerIndex]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * UsersApi - factory interface
 */
export const UsersApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = UsersApiFp(configuration);
  return {
    /**
     * Assigns a role to the user within the tenant.  The tenant defines the scope of the assignment. In other words, the role is effective only within the tenant.
     * @summary Assign Role To User
     * @param {UsersApiAssignRoleToUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    assignRoleToUser(
      requestParameters: UsersApiAssignRoleToUserRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<RoleAssignmentRead> {
      return localVarFp
        .assignRoleToUser(
          requestParameters.userId,
          requestParameters.projId,
          requestParameters.envId,
          requestParameters.userRoleCreate,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Creates a new user inside the Permit.io system, from that point forward you may run permission checks on that user.  Returns 201 if the user is created, 409 if the user already exists or if an inline role assignment names a tenant other than the one its resource instance already exists in. User is identified by its key, and you can only create one user with the same key inside a Permit environment.
     * @summary Create User
     * @param {UsersApiCreateUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    createUser(
      requestParameters: UsersApiCreateUserRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<UserRead> {
      return localVarFp
        .createUser(
          requestParameters.projId,
          requestParameters.envId,
          requestParameters.userCreate,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Deletes the user and all its related data.
     * @summary Delete User
     * @param {UsersApiDeleteUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    deleteUser(
      requestParameters: UsersApiDeleteUserRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .deleteUser(
          requestParameters.userId,
          requestParameters.projId,
          requestParameters.envId,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Gets a user, if such user exists. Otherwise returns 404.
     * @summary Get User
     * @param {UsersApiGetUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    getUser(
      requestParameters: UsersApiGetUserRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<UserRead> {
      return localVarFp
        .getUser(
          requestParameters.userId,
          requestParameters.projId,
          requestParameters.envId,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Lists all the users defined within an environment.
     * @summary List Users
     * @param {UsersApiListUsersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    listUsers(
      requestParameters: UsersApiListUsersRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<PaginatedResultUserRead> {
      return localVarFp
        .listUsers(
          requestParameters.projId,
          requestParameters.envId,
          requestParameters.search,
          requestParameters.searchOperator,
          requestParameters.role,
          requestParameters.includeResourceInstanceRoles,
          requestParameters.page,
          requestParameters.perPage,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Replace User / Sync User upsert a user in the system. If the user already exists, it will update the user with the new data. If the user does not exist, it will create a new user with the provided data.  The user is identified by its key, and you can only create one user with the same key inside a Permit environment. A 200 status code will be returned if the user already exists, and a 201 status code will be returned if the user is created.
     * @summary Replace User
     * @param {UsersApiReplaceUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    replaceUser(
      requestParameters: UsersApiReplaceUserRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<UserRead> {
      return localVarFp
        .replaceUser(
          requestParameters.userId,
          requestParameters.projId,
          requestParameters.envId,
          requestParameters.userCreate,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Unassigns the role from the user within the tenant.  The tenant defines the scope of the assignment. In other words, the role is effective only within the tenant.  If the role is not actually assigned, will return 404.
     * @summary Unassign Role From User
     * @param {UsersApiUnassignRoleFromUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    unassignRoleFromUser(
      requestParameters: UsersApiUnassignRoleFromUserRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<RoleAssignmentRead> {
      return localVarFp
        .unassignRoleFromUser(
          requestParameters.userId,
          requestParameters.projId,
          requestParameters.envId,
          requestParameters.userRoleRemove,
          requestParameters.returnDeleted,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     * Partially updates the user definition. Fields that will be provided will be completely overwritten.
     * @summary Update User
     * @param {UsersApiUpdateUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws If a required parameter is missing.
     */
    updateUser(
      requestParameters: UsersApiUpdateUserRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<UserRead> {
      return localVarFp
        .updateUser(
          requestParameters.userId,
          requestParameters.projId,
          requestParameters.envId,
          requestParameters.userUpdate,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * Request parameters for assignRoleToUser operation in UsersApi.
 */
export interface UsersApiAssignRoleToUserRequest {
  /**
   * Either the unique id of the user, or the URL-friendly key of the user (i.e: the \&quot;slug\&quot;).
   */
  readonly userId: string;

  /**
   * Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
   */
  readonly projId: string;

  /**
   * Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
   */
  readonly envId: string;

  readonly userRoleCreate: UserRoleCreate;
}

/**
 * Request parameters for createUser operation in UsersApi.
 */
export interface UsersApiCreateUserRequest {
  /**
   * Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
   */
  readonly projId: string;

  /**
   * Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
   */
  readonly envId: string;

  readonly userCreate: UserCreate;
}

/**
 * Request parameters for deleteUser operation in UsersApi.
 */
export interface UsersApiDeleteUserRequest {
  /**
   * Either the unique id of the user, or the URL-friendly key of the user (i.e: the \&quot;slug\&quot;).
   */
  readonly userId: string;

  /**
   * Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
   */
  readonly projId: string;

  /**
   * Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
   */
  readonly envId: string;
}

/**
 * Request parameters for getUser operation in UsersApi.
 */
export interface UsersApiGetUserRequest {
  /**
   * Either the unique id of the user, or the URL-friendly key of the user (i.e: the \&quot;slug\&quot;).
   */
  readonly userId: string;

  /**
   * Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
   */
  readonly projId: string;

  /**
   * Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
   */
  readonly envId: string;
}

/**
 * Request parameters for listUsers operation in UsersApi.
 */
export interface UsersApiListUsersRequest {
  /**
   * Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
   */
  readonly projId: string;

  /**
   * Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
   */
  readonly envId: string;

  /**
   * Text search for the user
   */
  readonly search?: string;

  /**
   * The search operator to use. &#x60;contains&#x60; performs a substring match on email, key, first_name, and last_name. &#x60;startswith&#x60; performs a prefix match on email, key, first_name, and last_name.
   */
  readonly searchOperator?: SearchOperator;

  /**
   * Match users with a specific role. To filter users without any roles, send an empty string.
   */
  readonly role?: string;

  /**
   * Should add resource instance roles
   */
  readonly includeResourceInstanceRoles?: boolean;

  /**
   * Page number of the results to fetch, starting at 1.
   */
  readonly page?: number;

  /**
   * The number of results per page (max 100).
   */
  readonly perPage?: number;
}

/**
 * Request parameters for replaceUser operation in UsersApi.
 */
export interface UsersApiReplaceUserRequest {
  /**
   * Either the unique id of the user, or the URL-friendly key of the user (i.e: the \&quot;slug\&quot;).
   */
  readonly userId: string;

  /**
   * Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
   */
  readonly projId: string;

  /**
   * Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
   */
  readonly envId: string;

  readonly userCreate: UserCreate;
}

/**
 * Request parameters for unassignRoleFromUser operation in UsersApi.
 */
export interface UsersApiUnassignRoleFromUserRequest {
  /**
   * Either the unique id of the user, or the URL-friendly key of the user (i.e: the \&quot;slug\&quot;).
   */
  readonly userId: string;

  /**
   * Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
   */
  readonly projId: string;

  /**
   * Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
   */
  readonly envId: string;

  readonly userRoleRemove: UserRoleRemove;

  /**
   * Whether to return the deleted role assignment, status code will be 200 instead of the default 204 if true
   */
  readonly returnDeleted?: boolean;
}

/**
 * Request parameters for updateUser operation in UsersApi.
 */
export interface UsersApiUpdateUserRequest {
  /**
   * Either the unique id of the user, or the URL-friendly key of the user (i.e: the \&quot;slug\&quot;).
   */
  readonly userId: string;

  /**
   * Either the unique id of the project, or the URL-friendly key of the project (i.e: the \&quot;slug\&quot;).
   */
  readonly projId: string;

  /**
   * Either the unique id of the environment, or the URL-friendly key of the environment (i.e: the \&quot;slug\&quot;).
   */
  readonly envId: string;

  readonly userUpdate: UserUpdate;
}

/**
 * UsersApi - object-oriented interface
 */
export class UsersApi extends BaseAPI {
  /**
   * Assigns a role to the user within the tenant.  The tenant defines the scope of the assignment. In other words, the role is effective only within the tenant.
   * @summary Assign Role To User
   * @param {UsersApiAssignRoleToUserRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public assignRoleToUser(
    requestParameters: UsersApiAssignRoleToUserRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return UsersApiFp(this.configuration)
      .assignRoleToUser(
        requestParameters.userId,
        requestParameters.projId,
        requestParameters.envId,
        requestParameters.userRoleCreate,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Creates a new user inside the Permit.io system, from that point forward you may run permission checks on that user.  Returns 201 if the user is created, 409 if the user already exists or if an inline role assignment names a tenant other than the one its resource instance already exists in. User is identified by its key, and you can only create one user with the same key inside a Permit environment.
   * @summary Create User
   * @param {UsersApiCreateUserRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public createUser(requestParameters: UsersApiCreateUserRequest, options?: RawAxiosRequestConfig) {
    return UsersApiFp(this.configuration)
      .createUser(
        requestParameters.projId,
        requestParameters.envId,
        requestParameters.userCreate,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Deletes the user and all its related data.
   * @summary Delete User
   * @param {UsersApiDeleteUserRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public deleteUser(requestParameters: UsersApiDeleteUserRequest, options?: RawAxiosRequestConfig) {
    return UsersApiFp(this.configuration)
      .deleteUser(
        requestParameters.userId,
        requestParameters.projId,
        requestParameters.envId,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Gets a user, if such user exists. Otherwise returns 404.
   * @summary Get User
   * @param {UsersApiGetUserRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public getUser(requestParameters: UsersApiGetUserRequest, options?: RawAxiosRequestConfig) {
    return UsersApiFp(this.configuration)
      .getUser(requestParameters.userId, requestParameters.projId, requestParameters.envId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Lists all the users defined within an environment.
   * @summary List Users
   * @param {UsersApiListUsersRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public listUsers(requestParameters: UsersApiListUsersRequest, options?: RawAxiosRequestConfig) {
    return UsersApiFp(this.configuration)
      .listUsers(
        requestParameters.projId,
        requestParameters.envId,
        requestParameters.search,
        requestParameters.searchOperator,
        requestParameters.role,
        requestParameters.includeResourceInstanceRoles,
        requestParameters.page,
        requestParameters.perPage,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Replace User / Sync User upsert a user in the system. If the user already exists, it will update the user with the new data. If the user does not exist, it will create a new user with the provided data.  The user is identified by its key, and you can only create one user with the same key inside a Permit environment. A 200 status code will be returned if the user already exists, and a 201 status code will be returned if the user is created.
   * @summary Replace User
   * @param {UsersApiReplaceUserRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public replaceUser(
    requestParameters: UsersApiReplaceUserRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return UsersApiFp(this.configuration)
      .replaceUser(
        requestParameters.userId,
        requestParameters.projId,
        requestParameters.envId,
        requestParameters.userCreate,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Unassigns the role from the user within the tenant.  The tenant defines the scope of the assignment. In other words, the role is effective only within the tenant.  If the role is not actually assigned, will return 404.
   * @summary Unassign Role From User
   * @param {UsersApiUnassignRoleFromUserRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public unassignRoleFromUser(
    requestParameters: UsersApiUnassignRoleFromUserRequest,
    options?: RawAxiosRequestConfig,
  ) {
    return UsersApiFp(this.configuration)
      .unassignRoleFromUser(
        requestParameters.userId,
        requestParameters.projId,
        requestParameters.envId,
        requestParameters.userRoleRemove,
        requestParameters.returnDeleted,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   * Partially updates the user definition. Fields that will be provided will be completely overwritten.
   * @summary Update User
   * @param {UsersApiUpdateUserRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws If a required parameter is missing.
   */
  public updateUser(requestParameters: UsersApiUpdateUserRequest, options?: RawAxiosRequestConfig) {
    return UsersApiFp(this.configuration)
      .updateUser(
        requestParameters.userId,
        requestParameters.projId,
        requestParameters.envId,
        requestParameters.userUpdate,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
