/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @interface APIHistoryEventFullRead
 */
export interface APIHistoryEventFullRead {
  /**
   *
   * @type {File}
   */
  request_body?: File;
  /**
   *
   * @type {File}
   */
  response_body?: File;
  /**
   *
   * @type {string}
   */
  timestamp: string;
  /**
   *
   * @type {string}
   */
  method: string;
  /**
   *
   * @type {string}
   */
  path: string;
  /**
   *
   * @type {boolean}
   */
  success: boolean;
  /**
   *
   * @type {number}
   */
  status: number;
  /**
   *
   * @type {string}
   */
  request_id?: string;
  /**
   *
   * @type {string}
   */
  client_ip: string;
  /**
   *
   * @type {string}
   */
  actor_type: string;
  /**
   *
   * @type {string}
   */
  actor_id: string;
  /**
   *
   * @type {string}
   */
  actor_display_name?: string;
  /**
   *
   * @type {string}
   */
  org_id?: string;
  /**
   *
   * @type {string}
   */
  project_key?: string;
  /**
   *
   * @type {string}
   */
  project_id?: string;
  /**
   *
   * @type {string}
   */
  env_key?: string;
  /**
   *
   * @type {string}
   */
  env_id?: string;
  /**
   *
   * @type {string}
   */
  id: string;
}
