/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An enumeration.
 * @export
 * @enum {string}
 */

export const APIKeyOwnerType = {
  PdpConfig: 'pdp_config',
  Member: 'member',
  Elements: 'elements',
} as const;

export type APIKeyOwnerType = typeof APIKeyOwnerType[keyof typeof APIKeyOwnerType];
