/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ActionObj } from './action-obj.js';
// May contain unused imports in some cases
// @ts-ignore
import { EnvironmentObject } from './environment-object.js';
// May contain unused imports in some cases
// @ts-ignore
import { OrganizationObject } from './organization-object.js';
// May contain unused imports in some cases
// @ts-ignore
import { PdpConfigObject } from './pdp-config-object.js';
// May contain unused imports in some cases
// @ts-ignore
import { ProjectObject } from './project-object.js';
// May contain unused imports in some cases
// @ts-ignore
import { ResourceTypeObj } from './resource-type-obj.js';
// May contain unused imports in some cases
// @ts-ignore
import { TenantObj } from './tenant-obj.js';
// May contain unused imports in some cases
// @ts-ignore
import { UserObj } from './user-obj.js';

/**
 *
 * @export
 * @interface AuditLogObjects
 */
export interface AuditLogObjects {
  /**
   *
   * @type {OrganizationObject}
   * @memberof AuditLogObjects
   */
  organization_object?: OrganizationObject;
  /**
   *
   * @type {ProjectObject}
   * @memberof AuditLogObjects
   */
  project_object?: ProjectObject;
  /**
   *
   * @type {EnvironmentObject}
   * @memberof AuditLogObjects
   */
  environment_object?: EnvironmentObject;
  /**
   *
   * @type {PdpConfigObject}
   * @memberof AuditLogObjects
   */
  pdp_config_object?: PdpConfigObject;
  /**
   *
   * @type {UserObj}
   * @memberof AuditLogObjects
   */
  user_object?: UserObj;
  /**
   *
   * @type {ActionObj}
   * @memberof AuditLogObjects
   */
  action_object?: ActionObj;
  /**
   *
   * @type {ResourceTypeObj}
   * @memberof AuditLogObjects
   */
  resource_type_object?: ResourceTypeObj;
  /**
   *
   * @type {TenantObj}
   * @memberof AuditLogObjects
   */
  tenant_object?: TenantObj;
}
