/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
import type { ActionObj } from './action-obj';
// May contain unused imports in some cases
import type { EnvironmentObject } from './environment-object';
// May contain unused imports in some cases
import type { OrganizationObject } from './organization-object';
// May contain unused imports in some cases
import type { PdpConfigObject } from './pdp-config-object';
// May contain unused imports in some cases
import type { ProjectObject } from './project-object';
// May contain unused imports in some cases
import type { ResourceTypeObj } from './resource-type-obj';
// May contain unused imports in some cases
import type { TenantObj } from './tenant-obj';
// May contain unused imports in some cases
import type { UserObj } from './user-obj';

export interface AuditLogObjectsModel {
  id?: string | null;
  organization_object?: OrganizationObject | null;
  project_object?: ProjectObject | null;
  environment_object?: EnvironmentObject | null;
  pdp_config_object?: PdpConfigObject | null;
  user_object?: UserObj | null;
  action_object?: ActionObj | null;
  resource_type_object?: ResourceTypeObj | null;
  tenant_object?: TenantObj | null;
  created_at?: string | null;
}
