/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * This is the data of a specific user in the system
 */
export interface DataGeneratorLibSchemasSchemaOpalDataUserData {
  /**
   * Key-Value mapping of the roles assigned to the user. The key is the tenant key and the value is a list of role keys assigned to the user in that tenant.
   * @deprecated
   */
  roleAssignments: { [key: string]: Array<string> };
  /**
   * Key-Value mapping of the attributes of the user. The key is the attribute key and the value is the attribute value.
   */
  attributes: object;
}
