/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { Data } from './data.js';

/**
 * Data source configuration - where client\'s should retrieve data from and how they should store it
 * @export
 * @interface DataSourceEntryWithPollingInterval
 */
export interface DataSourceEntryWithPollingInterval {
  /**
   * Url source to query for data
   * @type {string}
   * @memberof DataSourceEntryWithPollingInterval
   */
  url: string;
  /**
   *
   * @type {Data}
   * @memberof DataSourceEntryWithPollingInterval
   */
  data?: Data;
  /**
   * Suggested fetcher configuration (e.g. auth or method) to fetch data with
   * @type {object}
   * @memberof DataSourceEntryWithPollingInterval
   */
  config?: object;
  /**
   * topics the data applies to
   * @type {Array<string>}
   * @memberof DataSourceEntryWithPollingInterval
   */
  topics?: Array<string>;
  /**
   * OPA data api path to store the document at
   * @type {string}
   * @memberof DataSourceEntryWithPollingInterval
   */
  dst_path?: string;
  /**
   * Method used to write into OPA - PUT/PATCH
   * @type {string}
   * @memberof DataSourceEntryWithPollingInterval
   */
  save_method?: string;
  /**
   * Polling interval to refresh data from data source
   * @type {number}
   * @memberof DataSourceEntryWithPollingInterval
   */
  periodic_update_interval?: number;
}
