/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
import type { AuditLogObjectsModel } from './audit-log-objects-model';
// May contain unused imports in some cases
import type { RawData1 } from './raw-data1';

export interface DetailedAuditLogModel {
  id: string;
  raw_data: RawData1;
  timestamp: string;
  created_at?: string | null;
  query?: string | null;
  user_key?: string | null;
  user_email?: string | null;
  user_name?: string | null;
  resource_type?: string | null;
  tenant?: string | null;
  action?: string | null;
  decision?: boolean | null;
  reason?: string | null;
  org_id: string;
  project_id: string;
  env_id: string;
  pdp_config_id?: string | null;
  input?: any;
  result?: any;
  context?: any;
  objects?: AuditLogObjectsModel | null;
}
