/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
import type { ElementsConfigRead } from './elements-config-read';
// May contain unused imports in some cases
import type { ElementsPermissionLevel } from './elements-permission-level';

export interface ElementsConfigRuntimeRead {
  config: ElementsConfigRead;
  current_permission_level: ElementsPermissionLevel;
}
