/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
import type { UserInviteStatus } from './user-invite-status';

export interface ElementsUserInviteCreate {
  /**
   * The key of the user that is being invited
   */
  key: string;
  /**
   * The status of the user invite
   */
  status: UserInviteStatus;
  /**
   * The email of the user that being invited
   */
  email: string;
  /**
   * The first name of the user that is being invited
   */
  first_name: string;
  /**
   * The last name of the user that is being invited
   */
  last_name: string;
  /**
   * The role of the user that is being invited
   */
  role_id: string;
  /**
   * The tenant id of the user that is being invited
   */
  tenant_id: string;
  /**
   * The resource instance id of the user that is being invited
   */
  resource_instance_id: string;
}
