/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
import type { EmailMessageKeys } from './email-message-keys';

export interface EmailTemplateMessage {
  /**
   * The key of the message, can be either \'approval_flows_deny\', \'approval_flows_approve\', \'approval_flows_request\'
   */
  message_type: EmailMessageKeys;
  /**
   * The value of the message
   */
  message_content: string;
}
