/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
import type { EmailTemplateMessage } from './email-template-message';
// May contain unused imports in some cases
import type { EmailTemplateType } from './email-template-type';

export interface EmailTemplateRead {
  /**
   * The type of the email template, can be either \'approval_flows\' or \'user_management\'
   */
  template_type: EmailTemplateType;
  /**
   * Unique id of the EmailTemplate
   */
  id: string;
  /**
   * Unique id of the organization that the EmailTemplate belongs to.
   */
  organization_id: string;
  /**
   * Unique id of the project that the EmailTemplate belongs to.
   */
  project_id: string;
  /**
   * Unique id of the environment that the EmailTemplate belongs to.
   */
  environment_id: string;
  /**
   * The from address the mails will be sent from
   */
  from_address: string;
  /**
   * The redirect url the user will be redirected to after clicking the link in the email
   */
  redirect_to: string;
  /**
   * The time to live of the url in the email, in seconds
   */
  url_ttl: string;
  /**
   * The subject of the email template
   */
  subject: string;
  /**
   * The messages of the email template
   */
  messages: Array<EmailTemplateMessage>;
}
