/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EmbeddedLoginRequestOutput
 */
export interface EmbeddedLoginRequestOutput {
  /**
   * If the login request failed, this field will contain the error message
   * @type {string}
   * @memberof EmbeddedLoginRequestOutput
   */
  error?: string;
  /**
   * If the login request failed, this field will contain the error code
   * @type {number}
   * @memberof EmbeddedLoginRequestOutput
   */
  error_code?: number;
  /**
   * The auth token that lets your users login into permit elements
   * @type {string}
   * @memberof EmbeddedLoginRequestOutput
   */
  token?: string;
  /**
   * Extra data that you can pass to the login request
   * @type {string}
   * @memberof EmbeddedLoginRequestOutput
   */
  extra?: string;
  /**
   * The full URL to which the user should be redirected in order to complete the login process
   * @type {string}
   * @memberof EmbeddedLoginRequestOutput
   */
  redirect_url: string;
}
