/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { PDPConfigRead } from './pdpconfig-read';
// May contain unused imports in some cases
// @ts-ignore
import { Statistics } from './statistics';

/**
 *
 * @export
 * @interface EnvironmentStats
 */
export interface EnvironmentStats {
  /**
   * A URL-friendly name of the environment (i.e: slug). You will be able to query later using this key instead of the id (UUID) of the environment.
   * @type {string}
   * @memberof EnvironmentStats
   */
  key: string;
  /**
   * Unique id of the environment
   * @type {string}
   * @memberof EnvironmentStats
   */
  id: string;
  /**
   * Unique id of the organization that the environment belongs to.
   * @type {string}
   * @memberof EnvironmentStats
   */
  organization_id: string;
  /**
   * Unique id of the project that the environment belongs to.
   * @type {string}
   * @memberof EnvironmentStats
   */
  project_id: string;
  /**
   * Date and time when the environment was created (ISO_8601 format).
   * @type {string}
   * @memberof EnvironmentStats
   */
  created_at: string;
  /**
   * Date and time when the environment was last updated/modified (ISO_8601 format).
   * @type {string}
   * @memberof EnvironmentStats
   */
  updated_at: string;
  /**
   * The name of the environment
   * @type {string}
   * @memberof EnvironmentStats
   */
  name: string;
  /**
   * an optional longer description of the environment
   * @type {string}
   * @memberof EnvironmentStats
   */
  description?: string;
  /**
   * when using gitops feature, an optional branch name for the environment
   * @type {string}
   * @memberof EnvironmentStats
   */
  custom_branch_name?: string;
  /**
   *
   * @type {Array<PDPConfigRead>}
   * @memberof EnvironmentStats
   */
  pdp_configs: Array<PDPConfigRead>;
  /**
   *
   * @type {Statistics}
   * @memberof EnvironmentStats
   */
  stats: Statistics;
}
