/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @interface EnvironmentRegeneration
 */
export interface EnvironmentRegeneration {
  /**
   *
   * @type {string}
   */
  scope: EnvironmentRegenerationScopeEnum;
  /**
   *
   * @type {string}
   */
  org_id: string;
  /**
   *
   * @type {string}
   */
  proj_id: string;
  /**
   *
   * @type {string}
   */
  env_id: string;
}

export const EnvironmentRegenerationScopeEnum = {
  Environment: 'environment',
} as const;

export type EnvironmentRegenerationScopeEnum =
  (typeof EnvironmentRegenerationScopeEnum)[keyof typeof EnvironmentRegenerationScopeEnum];
