/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An enumeration.
 */

export const ErrorCode = {
  InvalidInput: 'INVALID_INPUT',
  InvalidJwksConfiguration: 'INVALID_JWKS_CONFIGURATION',
  UnexpectedError: 'UNEXPECTED_ERROR',
  NotFound: 'NOT_FOUND',
  DuplicateEntity: 'DUPLICATE_ENTITY',
  EmptyDecisionLogs: 'EMPTY_DECISION_LOGS',
  MissingRequestAttribute: 'MISSING_REQUEST_ATTRIBUTE',
  ForbiddenAccess: 'FORBIDDEN_ACCESS',
  InvalidPermissionFormat: 'INVALID_PERMISSION_FORMAT',
  MissingPermissions: 'MISSING_PERMISSIONS',
  UnsupportedAttributeType: 'UNSUPPORTED_ATTRIBUTE_TYPE',
  MissingResourceAttribute: 'MISSING_RESOURCE_ATTRIBUTE',
  MismatchAttributesTypes: 'MISMATCH_ATTRIBUTES_TYPES',
  InvalidPolicyRepoStatus: 'INVALID_POLICY_REPO_STATUS',
  InvalidSmtpConfiguration: 'INVALID_SMTP_CONFIGURATION',
  MismatchResourceInstancesTenants: 'MISMATCH_RESOURCE_INSTANCES_TENANTS',
  PaginationSizeOverreached: 'PAGINATION_SIZE_OVERREACHED',
  MismatchRelationType: 'MISMATCH_RELATION_TYPE',
  ConcurrentOperationDisallowed: 'CONCURRENT_OPERATION_DISALLOWED',
  Unauthorized: 'UNAUTHORIZED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
