/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Generic decision log format for external or custom integrations.  Accepts a flat JSON payload with explicit fields rather than requiring engine-specific nested structures. Unknown fields are rejected to prevent unbounded storage growth.
 */
export interface GenericEngineDecisionLog {
  engine?: GenericEngineDecisionLogEngineEnum | null;
  timestamp: string;
  decision: boolean;
  decision_id?: string | null;
  process_time_ms?: number | null;
  query?: string | null;
  user_key?: string | null;
  user_email?: string | null;
  user_name?: string | null;
  action?: string | null;
  resource_type?: string | null;
  tenant?: string | null;
  input?: any;
  result?: any;
  context?: any;
}

export const GenericEngineDecisionLogEngineEnum = {
  Generic: 'GENERIC',
} as const;

export type GenericEngineDecisionLogEngineEnum =
  (typeof GenericEngineDecisionLogEngineEnum)[keyof typeof GenericEngineDecisionLogEngineEnum];
