/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { InviteStatus } from './invite-status';

/**
 *
 * @export
 * @interface InviteRead
 */
export interface InviteRead {
  /**
   * The invited member\'s email address
   * @type {string}
   * @memberof InviteRead
   */
  email: string;
  /**
   * The role the member will be assigned with
   * @type {string}
   * @memberof InviteRead
   */
  role: string;
  /**
   * Unique id of the invite
   * @type {string}
   * @memberof InviteRead
   */
  id: string;
  /**
   * Unique id of the organization that the invite belongs to.
   * @type {string}
   * @memberof InviteRead
   */
  organization_id: string;
  /**
   * The invite code that is sent to the member\'s email
   * @type {string}
   * @memberof InviteRead
   */
  invite_code: string;
  /**
   * Date and time when the invite was created (ISO_8601 format).
   * @type {string}
   * @memberof InviteRead
   */
  created_at: string;
  /**
   * The status of the invite (pending, failed, etc)
   * @type {InviteStatus}
   * @memberof InviteRead
   */
  status: InviteStatus;
  /**
   * if failed, the reason the invitation failed
   * @type {string}
   * @memberof InviteRead
   */
  failed_reason?: string;
}
