/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
import type { InviteStatus } from './invite-status';
// May contain unused imports in some cases
import type { MemberAccessLevel } from './member-access-level';

export interface InviteRead {
  /**
   * Unique id of the invite
   */
  member_id?: string;
  /**
   * The invited member\'s email address
   */
  email: string;
  /**
   * The role the member will be assigned with
   */
  role?: MemberAccessLevel;
  /**
   * Unique id of the invite
   */
  id: string;
  /**
   * Unique id of the organization that the invite belongs to.
   */
  organization_id: string;
  /**
   * The invite code that is sent to the member\'s email
   */
  invite_code: string;
  /**
   * Date and time when the invite was created (ISO_8601 format).
   */
  created_at: string;
  /**
   * The status of the invite (pending, failed, etc)
   */
  status: InviteStatus;
  /**
   * if failed, the reason the invitation failed
   */
  failed_reason?: string;
}
