/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { MemberAccessLevel } from './member-access-level.js';

/**
 *
 * @export
 * @interface InviteCreate
 */
export interface InviteCreate {
  /**
   * Unique id of the invite
   * @type {string}
   * @memberof InviteCreate
   */
  member_id?: string;
  /**
   * The invited member\'s email address
   * @type {string}
   * @memberof InviteCreate
   */
  email: string;
  /**
   * The role the member will be assigned with
   * @type {MemberAccessLevel}
   * @memberof InviteCreate
   */
  role?: MemberAccessLevel;
}
