/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
import type { Methods } from './methods';

export interface MappingRule {
  /**
   * The URL to match against the request URL
   */
  url: string;
  /**
   * The URL type to match against the request URL can be, \'regex\' or none
   */
  url_type?: MappingRuleUrlTypeEnum;
  /**
   * The HTTP method to match against the request method
   */
  http_method: Methods;
  /**
   * The resource to match against the request resource
   */
  resource: string;
  /**
   * The headers to match against the request headers
   */
  headers?: { [key: string]: string };
  /**
   * The action to match against the request action
   */
  action?: string;
  /**
   * The priority of the mapping rule. The higher the priority, the higher the precedence
   */
  priority?: number;
}

export const MappingRuleUrlTypeEnum = {
  Regex: 'regex',
} as const;

export type MappingRuleUrlTypeEnum =
  (typeof MappingRuleUrlTypeEnum)[keyof typeof MappingRuleUrlTypeEnum];
