/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { Permission } from './permission';

/**
 *
 * @export
 * @interface OrgMemberRemovePermissions
 */
export interface OrgMemberRemovePermissions {
  /**
   * Unique id of the account member
   * @type {string}
   * @memberof OrgMemberRemovePermissions
   */
  id: string;
  /**
   *
   * @type {Array<Permission>}
   * @memberof OrgMemberRemovePermissions
   */
  permissions: Array<Permission>;
}
