/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
import type { IdentityRead } from './identity-read';
// May contain unused imports in some cases
import type { InviteRead } from './invite-read';
// May contain unused imports in some cases
import type { OnboardingStep } from './onboarding-step';

export interface OrgMemberRead {
  /**
   * Unique id of the account member
   */
  id: string;
  /**
   * Email of the user controlling this account
   */
  email: string;
  /**
   * Whether this email address is verified or not. For social providers like \'Login with Google\' this is done automatically, otherwise we will send the user a verification link in email.
   */
  email_verified: boolean;
  /**
   * Name of this user
   */
  name?: string;
  /**
   * First name of the user
   */
  given_name?: string;
  /**
   * Last name of the user
   */
  family_name?: string;
  /**
   * URL to picture, photo, or avatar of the user that controls this account.
   */
  picture?: string;
  /**
   * Whether or not this user has special access to permit.io organizations
   */
  is_superuser: boolean;
  /**
   * Whether or not this user is currently onboarding, needs to be replaced by a user journey object
   */
  is_onboarding: boolean;
  /**
   * the step the user is currently going through in onboarding
   */
  onboarding_step: OnboardingStep;
  /**
   * Date and time when the account member was created (ISO_8601 format).
   */
  created_at: string;
  /**
   * Last date and time this user logged in (ISO_8601 format).
   */
  last_login?: string;
  /**
   * Last IP address from which this user logged in.
   */
  last_ip?: string;
  /**
   * Total number of logins this user has performed.
   */
  logins_count?: number;
  identities: Array<IdentityRead>;
  invite?: InviteRead;
  /**
   * Custom permit.io dashboard settings, such as preferred theme, etc.
   */
  settings: object;
}
