/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PDPContext
 */
export interface PDPContext {
  /**
   *
   * @type {string}
   * @memberof PDPContext
   */
  customer_id: string;
  /**
   *
   * @type {string}
   * @memberof PDPContext
   */
  client_id: string;
  /**
   *
   * @type {string}
   * @memberof PDPContext
   */
  backend_tier: string;
  /**
   *
   * @type {string}
   * @memberof PDPContext
   */
  component?: string;
}
