/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @interface PDPConfigRead
 */
export interface PDPConfigRead {
  /**
   *
   * @type {string}
   */
  id: string;
  /**
   *
   * @type {string}
   */
  name?: string;
  /**
   * Unique id of the organization that the pdp_config belongs to.
   * @type {string}
   */
  organization_id: string;
  /**
   * Unique id of the project that the pdp_config belongs to.
   * @type {string}
   */
  project_id: string;
  /**
   * Unique id of the environment that the pdp_config belongs to.
   * @type {string}
   */
  environment_id: string;
  /**
   *
   * @type {string}
   */
  client_secret: string;
}
