/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @interface PDPInfo
 */
export interface PDPInfo {
  /**
   *
   * @type {string}
   */
  version?: string;
  /**
   *
   * @type {string}
   */
  os_name?: string;
  /**
   *
   * @type {string}
   */
  os_release?: string;
  /**
   *
   * @type {string}
   */
  os_version?: string;
  /**
   *
   * @type {string}
   */
  os_platform?: string;
  /**
   *
   * @type {string}
   */
  os_machine?: string;
  /**
   *
   * @type {string}
   */
  python_version?: string;
  /**
   *
   * @type {string}
   */
  python_implementation?: string;
}
