/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ProjectObj } from './project-obj';

/**
 *
 * @export
 * @interface ProjectObject
 */
export interface ProjectObject {
  /**
   *
   * @type {string}
   * @memberof ProjectObject
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ProjectObject
   */
  key: string;
  /**
   *
   * @type {string}
   * @memberof ProjectObject
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof ProjectObject
   */
  created_at: string;
  /**
   *
   * @type {string}
   * @memberof ProjectObject
   */
  updated_at: string;
}
