/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ProjectUpdate
 */
export interface ProjectUpdate {
  /**
   * The name of the project
   * @type {string}
   * @memberof ProjectUpdate
   */
  name?: string;
  /**
   * a longer description outlining the project objectives
   * @type {string}
   * @memberof ProjectUpdate
   */
  description?: string;
  /**
   * the settings for this project
   * @type {object}
   * @memberof ProjectUpdate
   */
  settings?: object;
  /**
   * the id of the policy repo to use for this project
   * @type {string}
   * @memberof ProjectUpdate
   */
  active_policy_repo_id?: string;
}
