/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ProjectRead {
  /**
   * A URL-friendly name of the project (i.e: slug). You will be able to query later using this key instead of the id (UUID) of the project.
   */
  key: string;
  /**
   * Optional namespace for URNs. If empty, URNs will be generated from project key.
   */
  urn_namespace?: string;
  /**
   * Unique id of the project
   */
  id: string;
  /**
   * Unique id of the organization that the project belongs to.
   */
  organization_id: string;
  /**
   * Date and time when the project was created (ISO_8601 format).
   */
  created_at: string;
  /**
   * Date and time when the project was last updated/modified (ISO_8601 format).
   */
  updated_at: string;
  /**
   * The name of the project
   */
  name: string;
  /**
   * a longer description outlining the project objectives
   */
  description?: string;
  /**
   * the settings for this project
   */
  settings?: object;
  /**
   * the id of the policy repo to use for this project
   */
  active_policy_repo_id?: string;
}
