/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ProjectUpdate {
  /**
   * The name of the project
   */
  name?: string;
  /**
   * a longer description outlining the project objectives
   */
  description?: string;
  /**
   * the settings for this project
   */
  settings?: object;
  /**
   * the id of the policy repo to use for this project
   */
  active_policy_repo_id?: string;
}
