/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
import type { AuthMechanism } from './auth-mechanism';
// May contain unused imports in some cases
import type { MappingRuleUpdate } from './mapping-rule-update';
// May contain unused imports in some cases
import type { Secret } from './secret';

export interface ProxyConfigUpdate {
  secret?: Secret;
  /**
   * The name of the proxy config, for example: \'Stripe API\'
   */
  name?: string;
  /**
   * Proxy config mapping rules, with optional should_delete flag to indicate deletion.
   */
  mapping_rules?: Array<MappingRuleUpdate>;
  /**
   * Proxy config auth mechanism will define the authentication mechanism that will be used to authenticate the request.  Bearer injects the secret into the Authorization header as a Bearer token,  Basic injects the secret into the Authorization header as a Basic user:password,  Headers injects plain headers into the request.
   */
  auth_mechanism?: AuthMechanism;
}
