/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { DummyEngineModel } from './dummy-engine-model';
// May contain unused imports in some cases
// @ts-ignore
import { Engine } from './engine';
// May contain unused imports in some cases
// @ts-ignore
import { OPAEngineDecisionLog } from './opaengine-decision-log';
// May contain unused imports in some cases
// @ts-ignore
import { OPALabels } from './opalabels';
// May contain unused imports in some cases
// @ts-ignore
import { OPAMetrics } from './opametrics';

/**
 *
 * @export
 * @interface RawData
 */
export interface RawData {
  /**
   *
   * @type {Engine}
   * @memberof RawData
   */
  engine?: Engine;
  /**
   *
   * @type {string}
   * @memberof RawData
   */
  decision_id: string;
  /**
   *
   * @type {OPALabels}
   * @memberof RawData
   */
  labels: OPALabels;
  /**
   *
   * @type {string}
   * @memberof RawData
   */
  timestamp: string;
  /**
   *
   * @type {string}
   * @memberof RawData
   */
  path: string;
  /**
   *
   * @type {any}
   * @memberof RawData
   */
  input?: any;
  /**
   *
   * @type {any}
   * @memberof RawData
   */
  result?: any;
  /**
   *
   * @type {OPAMetrics}
   * @memberof RawData
   */
  metrics: OPAMetrics;
}
