/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ResourceRoleUpdate
 */
export interface ResourceRoleUpdate {
  /**
   * The name of the role
   * @type {string}
   * @memberof ResourceRoleUpdate
   */
  name?: string;
  /**
   * optional description string explaining what this role represents, or what permissions are granted to it.
   * @type {string}
   * @memberof ResourceRoleUpdate
   */
  description?: string;
  /**
   * list of action keys that define what actions this resource role is permitted to do
   * @type {Array<string>}
   * @memberof ResourceRoleUpdate
   */
  permissions?: Array<string>;
  /**
   * list of role keys that define what roles this role extends. In other words: this role will automatically inherit all the permissions of the given roles in this list.
   * @type {Array<string>}
   * @memberof ResourceRoleUpdate
   */
  extends?: Array<string>;
}
