/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ResourceInstanceBlockRead {
  /**
   * A unique identifier by which Permit will identify the resource instance for permission checks. You will later pass this identifier to the `permit.check()` API. A key can be anything: for example the resource db id, a url slug, a UUID or anything else as long as it\'s unique on your end. The resource instance key must be url-friendly.
   */
  key: string;
  /**
   * the *key* of the tenant that this resource belongs to, used to enforce tenant boundaries in multi-tenant apps.
   */
  tenant: string;
  /**
   * the *key* of the resource (type) of this resource instance. For example: if this resource instance is the annual budget document, the key of the resource might be `document`.
   */
  resource: string;
  /**
   * Arbitrary resource attributes that will be used to enforce attribute-based access control policies.
   */
  attributes?: object;
}
