/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ResourceActionGroupRead
 */
export interface ResourceActionGroupRead {
  /**
   * The name of the action group
   * @type {string}
   * @memberof ResourceActionGroupRead
   */
  name: string;
  /**
   * An optional longer description of what this action group represents in your system
   * @type {string}
   * @memberof ResourceActionGroupRead
   */
  description?: string;
  /**
   * optional dictionary of key-value pairs that can be used to store arbitrary metadata about this action group. This metadata can be used to filter action groups using query parameters with attr_ prefix
   * @type {object}
   * @memberof ResourceActionGroupRead
   */
  attributes?: object;
  /**
   *
   * @type {Array<string>}
   * @memberof ResourceActionGroupRead
   */
  actions?: Array<string>;
  /**
   * A URL-friendly name of the action group (i.e: slug). You will be able to query later using this key instead of the id (UUID) of the action group.
   * @type {string}
   * @memberof ResourceActionGroupRead
   */
  key: string;
  /**
   * Unique id of the action group
   * @type {string}
   * @memberof ResourceActionGroupRead
   */
  id: string;
  /**
   * Unique id of the organization that the action group belongs to.
   * @type {string}
   * @memberof ResourceActionGroupRead
   */
  organization_id: string;
  /**
   * Unique id of the project that the action group belongs to.
   * @type {string}
   * @memberof ResourceActionGroupRead
   */
  project_id: string;
  /**
   * Unique id of the environment that the action group belongs to.
   * @type {string}
   * @memberof ResourceActionGroupRead
   */
  environment_id: string;
  /**
   * Unique id of the resource that the action group belongs to.
   * @type {string}
   * @memberof ResourceActionGroupRead
   */
  resource_id: string;
  /**
   * Date and time when the action group was created (ISO_8601 format).
   * @type {string}
   * @memberof ResourceActionGroupRead
   */
  created_at: string;
  /**
   * Date and time when the action group was last updated/modified (ISO_8601 format).
   * @type {string}
   * @memberof ResourceActionGroupRead
   */
  updated_at: string;
}
