/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { EnvironmentCopyScopeFilters } from './environment-copy-scope-filters.js';

/**
 * @type ResourceSets
 * Resource sets to copy
 * @export
 */
export type ResourceSets = EnvironmentCopyScopeFilters;
