/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
import type { PaginatedResultRoleAssignmentDetailedRead } from './paginated-result-role-assignment-detailed-read';
// May contain unused imports in some cases
import type { PaginatedResultRoleAssignmentRead } from './paginated-result-role-assignment-read';
// May contain unused imports in some cases
import type { RoleAssignmentDetailedRead } from './role-assignment-detailed-read';
// May contain unused imports in some cases
import type { RoleAssignmentRead } from './role-assignment-read';

export type ResponseListRoleAssignmentsV2FactsProjIdEnvIdRoleAssignmentsGet =
  | Array<RoleAssignmentDetailedRead>
  | Array<RoleAssignmentRead>
  | PaginatedResultRoleAssignmentDetailedRead
  | PaginatedResultRoleAssignmentRead;
