/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
import type { RoleAssignmentResourceInstance } from './role-assignment-resource-instance';
// May contain unused imports in some cases
import type { RoleAssignmentRole } from './role-assignment-role';
// May contain unused imports in some cases
import type { RoleAssignmentTenant } from './role-assignment-tenant';
// May contain unused imports in some cases
import type { RoleAssignmentUser } from './role-assignment-user';

export interface RoleAssignmentDetailedRead {
  /**
   * Unique id of the role assignment
   */
  id: string;
  /**
   * the role that is assigned
   */
  role: RoleAssignmentRole;
  /**
   * the user the role is assigned to
   */
  user: RoleAssignmentUser;
  /**
   * the tenant the role is associated with
   */
  tenant: RoleAssignmentTenant;
  resource_instance?: RoleAssignmentResourceInstance;
  /**
   * Unique id of the organization that the role assignment belongs to.
   */
  organization_id: string;
  /**
   * Unique id of the project that the role assignment belongs to.
   */
  project_id: string;
  /**
   * Unique id of the environment that the role assignment belongs to.
   */
  environment_id: string;
  /**
   * Date and time when the role assignment was created (ISO_8601 format).
   */
  created_at: string;
}
