/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RoleAssignmentRead
 */
export interface RoleAssignmentRead {
  /**
   * Unique id of the role assignment
   * @type {string}
   * @memberof RoleAssignmentRead
   */
  id: string;
  /**
   * the user the role is assigned to
   * @type {string}
   * @memberof RoleAssignmentRead
   */
  user: string;
  /**
   * the role that is assigned
   * @type {string}
   * @memberof RoleAssignmentRead
   */
  role: string;
  /**
   * the tenant the role is associated with
   * @type {string}
   * @memberof RoleAssignmentRead
   */
  tenant?: string;
  /**
   * the resource type the role is associated with
   * @type {string}
   * @memberof RoleAssignmentRead
   */
  resource?: string;
  /**
   * the resource instance the role is associated with
   * @type {string}
   * @memberof RoleAssignmentRead
   */
  resource_instance?: string;
  /**
   * Unique id of the resource type
   * @type {string}
   * @memberof RoleAssignmentRead
   */
  resource_id?: string;
  /**
   * Unique id of the resource instance
   * @type {string}
   * @memberof RoleAssignmentRead
   */
  resource_instance_id?: string;
  /**
   * Unique id of the user
   * @type {string}
   * @memberof RoleAssignmentRead
   */
  user_id: string;
  /**
   * Unique id of the role
   * @type {string}
   * @memberof RoleAssignmentRead
   */
  role_id: string;
  /**
   * Unique id of the tenant
   * @type {string}
   * @memberof RoleAssignmentRead
   */
  tenant_id: string;
  /**
   * Unique id of the organization that the role assignment belongs to.
   * @type {string}
   * @memberof RoleAssignmentRead
   */
  organization_id: string;
  /**
   * Unique id of the project that the role assignment belongs to.
   * @type {string}
   * @memberof RoleAssignmentRead
   */
  project_id: string;
  /**
   * Unique id of the environment that the role assignment belongs to.
   * @type {string}
   * @memberof RoleAssignmentRead
   */
  environment_id: string;
  /**
   * Date and time when the role assignment was created (ISO_8601 format).
   * @type {string}
   * @memberof RoleAssignmentRead
   */
  created_at: string;
}
