/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @interface TenantObj
 */
export interface TenantObj {
  /**
   *
   * @type {string}
   */
  id: string;
  /**
   *
   * @type {string}
   */
  key: string;
  /**
   *
   * @type {string}
   */
  name?: string;
  /**
   *
   * @type {object}
   */
  attributes?: object;
  /**
   *
   * @type {string}
   */
  created_at: string;
  /**
   *
   * @type {string}
   */
  updated_at: string;
}
