/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TenantBlockRead {
  /**
   * A unique id by which Permit will identify the tenant. The tenant key must be url-friendly (slugified).
   */
  key: string;
  /**
   * A descriptive name for the tenant
   */
  name: string;
  /**
   * an optional longer description of the tenant
   */
  description?: string;
  /**
   * Arbitrary tenant attributes that will be used to enforce
   * attribute-based access control policies.
   */
  attributes?: object;
}
