/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserUpdate {
  /**
   * The email of the user. If synced, will be unique inside the environment.
   */
  email?: string;
  /**
   * First name of the user.
   */
  first_name?: string;
  /**
   * Last name of the user.
   */
  last_name?: string;
  /**
   * Arbitrary user attributes that will be used to enforce attribute-based access control policies.
   */
  attributes?: object;
}
