/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
import type { UserInTenant } from './user-in-tenant';
// May contain unused imports in some cases
import type { UserRole } from './user-role';

export interface UserRead {
  /**
   * A unique id by which Permit will identify the user for permission checks.
   */
  key: string;
  /**
   * Unique id of the user
   */
  id: string;
  /**
   * Unique id of the organization that the user belongs to.
   */
  organization_id: string;
  /**
   * Unique id of the project that the user belongs to.
   */
  project_id: string;
  /**
   * Unique id of the environment that the user belongs to.
   */
  environment_id: string;
  associated_tenants?: Array<UserInTenant>;
  /**
   * @deprecated
   */
  roles?: Array<UserRole>;
  /**
   * Date and time when the user was created (ISO_8601 format).
   */
  created_at: string;
  /**
   * Date and time when the user was last updated/modified (ISO_8601 format).
   */
  updated_at: string;
  /**
   * The email of the user. If synced, will be unique inside the environment.
   */
  email?: string;
  /**
   * First name of the user.
   */
  first_name?: string;
  /**
   * Last name of the user.
   */
  last_name?: string;
  /**
   * Arbitrary user attributes that will be used to enforce attribute-based access control policies.
   */
  attributes?: object;
}
