/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases

// May contain unused imports in some cases
import { type APIKeyViewerContext } from './apikey-viewer-context';
// May contain unused imports in some cases

// May contain unused imports in some cases
import { type MemberViewerContext } from './member-viewer-context';

/**
 * @type Viewer
 */
export type Viewer =
  | ({ type: 'api_key' } & APIKeyViewerContext)
  | ({ type: 'member' } & MemberViewerContext);
