/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
import { MemberAccessLevel } from './member-access-level';
// May contain unused imports in some cases
import { MemberAccessObj } from './member-access-obj';

/**
 *
 * @interface ViewerGrant
 */
export interface ViewerGrant {
  /**
   *
   * @type {MemberAccessLevel}
   */
  role: MemberAccessLevel;
  /**
   *
   * @type {MemberAccessObj}
   */
  type: MemberAccessObj;
  /**
   *
   * @type {string}
   */
  org_id?: string;
  /**
   *
   * @type {string}
   */
  project_id?: string;
  /**
   *
   * @type {string}
   */
  env_id?: string;
}
