/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { APIKeyInfo } from './apikey-info.js';
// May contain unused imports in some cases
// @ts-ignore
import { APIKeyViewerContext } from './apikey-viewer-context.js';
// May contain unused imports in some cases
// @ts-ignore
import { MemberInfo } from './member-info.js';
// May contain unused imports in some cases
// @ts-ignore
import { MemberViewerContext } from './member-viewer-context.js';

/**
 * @type Viewer
 * @export
 */
export type Viewer =
  | ({ type: 'api_key' } & APIKeyViewerContext)
  | ({ type: 'member' } & MemberViewerContext);
