/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { Viewer } from './viewer';
// May contain unused imports in some cases
// @ts-ignore
import { ViewerGrant } from './viewer-grant';

/**
 * A Viewer Context object represents the currently logged in actor.  - It can be a human user of permit.io - It can be a machine (using an api key) that directly interacts with the api - It can be an (embedded) human user of one of our customers, using an embedded UI interface.  A VC object should contain *all* the data required by the internal authz layer to verify whether an api request is allowed to run.  This model allows us to avoid expensive SQL queries for internal AuthZ logic.
 * @export
 * @interface ViewerContext
 */
export interface ViewerContext {
  /**
   *
   * @type {Viewer}
   * @memberof ViewerContext
   */
  viewer: Viewer;
  /**
   *
   * @type {Array<ViewerGrant>}
   * @memberof ViewerContext
   */
  grants: Array<ViewerGrant>;
  /**
   * the active organization id
   * @type {string}
   * @memberof ViewerContext
   */
  active_org_id?: string;
}
