/* tslint:disable */
/* eslint-disable */
/**
 * Permit.io API
 *  Authorization as a service
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface WebhookCreate
 */
export interface WebhookCreate {
  /**
   * The url to POST the webhook to
   * @type {string}
   * @memberof WebhookCreate
   */
  url: string;
  /**
   * An optional bearer token to use to authenticate the request
   * @type {string}
   * @memberof WebhookCreate
   */
  bearer_token?: string;
}
